export const products = [
  // Electronics
  {
    id: 1,
    name: 'Like-New Echo Dot (5th Gen, 2022 release)',
    category: 'Electronics',
    price: 49.99,
    rating: 4.7,
    reviews: 15234,
    image: 'https://m.media-amazon.com/images/I/71W2eDGsAJL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Like-New-release-vibrant-helpful-routines/dp/B09RX3512T',
    description: 'Smart speaker with Alexa featuring vibrant sound, voice control, and seamless smart home integration',
    longDescription: 'Smart speaker with Alexa featuring vibrant sound, voice control, and seamless smart home integration. Control your smart home devices, play music, answer questions, and more with just your voice.',
    features: ['Alexa voice control', 'Improved audio quality', 'Smart home hub', 'Music streaming'],
    specs: { Brand: 'Amazon', Model: 'Echo Dot 5th Gen', Connectivity: 'Wi-Fi, Bluetooth', Color: 'Charcoal' }
  },
  {
    id: 2,
    name: 'Amazon Fire TV Stick 4K Select (newest model)',
    category: 'Electronics',
    price: 54.99,
    rating: 4.6,
    reviews: 8912,
    image: 'https://m.media-amazon.com/images/I/71B2hSrvyZL._AC_SY450_.jpg',
    link: 'https://www.amazon.com/amazon-fire-tv-stick-4K-select/dp/B0C6W3D4RM',
    description: 'Stream in stunning 4K Ultra HD with support for Dolby Vision, HDR10+, and immersive Dolby Atmos audio',
    longDescription: 'Stream in stunning 4K Ultra HD with support for Dolby Vision, HDR10+, and immersive Dolby Atmos audio. Access thousands of channels, apps, and Alexa skills with this powerful streaming device.',
    features: ['4K Ultra HD streaming', 'Dolby Vision & HDR10+', 'Dolby Atmos audio', 'Alexa voice remote'],
    specs: { Resolution: '4K Ultra HD', Streaming: 'Wi-Fi 6', Voice: 'Alexa', Storage: '8GB' }
  },
  {
    id: 3,
    name: 'Apple AirPods Pro 2 Wireless Earbuds',
    category: 'Electronics',
    price: 249.99,
    originalPrice: 299.99,
    rating: 4.8,
    reviews: 32456,
    image: 'https://m.media-amazon.com/images/I/611pEx7220L._AC_SX522_.jpg',
    link: 'https://www.amazon.com/Apple-Cancellation-Transparency-Personalized-High-Fidelity/dp/B0D1XD1ZV3',
    description: 'Premium wireless earbuds with adaptive active noise cancellation, transparency mode, and personalized spatial audio',
    longDescription: 'Premium wireless earbuds with up to 2x more active noise cancellation than the previous generation. Features Adaptive Audio that automatically adjusts noise control to your environment and personalized spatial audio for an immersive listening experience.',
    features: ['Active Noise Cancellation', 'Adaptive Audio', 'Transparency mode', 'Personalized Spatial Audio', 'Up to 6 hours listening time'],
    specs: { Brand: 'Apple', Model: 'AirPods Pro 2', Battery: 'Up to 30 hours with case', Connectivity: 'Bluetooth 5.3' }
  },
  {
    id: 4,
    name: 'Anker Power Bank (PowerCore 10K)',
    category: 'Electronics',
    price: 29.99,
    rating: 4.7,
    reviews: 18765,
    image: 'https://m.media-amazon.com/images/I/71JJLJnwREL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Anker-Travel-Ready-Technology-High-Speed-Output%EF%BC%88Black%EF%BC%89%EF%BC%8C1pack/dp/B0D5CLSMFB',
    description: 'Ultra-compact 10,000mAh portable charger with PowerIQ technology for fast charging on the go',
    longDescription: 'Ultra-compact 10,000mAh portable charger with PowerIQ technology that intelligently identifies your device for the fastest possible charge. Slim design fits easily in pockets and bags while providing multiple full phone charges.',
    features: ['10,000mAh capacity', 'PowerIQ fast charging', 'Ultra-compact design', 'Universal compatibility'],
    specs: { Capacity: '10,000mAh', Output: '12W', Weight: '6.56 oz', Ports: 'USB-A' }
  },
  {
    id: 5,
    name: 'SAMSUNG Galaxy S25 Ultra',
    category: 'Electronics',
    price: 1299.99,
    rating: 4.9,
    reviews: 4567,
    image: 'https://m.media-amazon.com/images/I/61n0lmxP5-L._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Smartphone-Unlocked-Processor-Manufacturer-Warranty/dp/B0DP3G4GVQ',
    description: 'Flagship unlocked smartphone with advanced processor, stunning display, and professional-grade camera system',
    longDescription: 'Flagship unlocked smartphone featuring the latest Snapdragon processor, stunning 6.8-inch Dynamic AMOLED display with 120Hz refresh rate, and a professional quad-camera system with advanced AI features for stunning photos and videos.',
    features: ['6.8" Dynamic AMOLED display', 'Snapdragon processor', 'Quad camera system', '5000mAh battery', 'S Pen included'],
    specs: { Display: '6.8" AMOLED', Storage: '256GB', RAM: '12GB', Camera: '200MP main' }
  },

  // Home & Kitchen
  {
    id: 6,
    name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker',
    category: 'Home & Kitchen',
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.7,
    reviews: 142567,
    image: 'https://m.media-amazon.com/images/I/71Z401LjFFL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Instant-Pot-Multi-Use-Programmable-Pressure/dp/B00FLYWNYQ',
    description: 'Multi-functional programmable cooker combining pressure cooker, slow cooker, rice cooker, steamer, and more',
    longDescription: '7-in-1 programmable cooker that replaces multiple kitchen appliances. Functions as pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and warmer. Makes cooking fast, easy, and convenient.',
    features: ['7-in-1 functionality', '14 smart programs', '6-quart capacity', 'Stainless steel pot'],
    specs: { Capacity: '6 Quart', Functions: '7-in-1', Wattage: '1000W', Material: 'Stainless Steel' }
  },
  {
    id: 7,
    name: 'Ninja Air Fryer',
    category: 'Home & Kitchen',
    price: 89.99,
    rating: 4.8,
    reviews: 67234,
    image: 'https://m.media-amazon.com/images/I/71+8uTMDRFL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Ninja-AF101-Fryer-Black-gray/dp/B07FDJMC9Q',
    description: 'Compact air fryer with wide temperature range for guilt-free crispy favorites using little to no oil',
    longDescription: 'Compact yet powerful air fryer that uses rapid air circulation technology to cook food with up to 75% less fat than traditional frying methods. Wide temperature range allows for versatile cooking from dehydrating to air frying.',
    features: ['4-quart capacity', '400°F max temperature', 'Dishwasher safe basket', 'Compact design'],
    specs: { Capacity: '4 Quart', Temperature: '105-400°F', Wattage: '1550W', Coating: 'Nonstick' }
  },
  {
    id: 8,
    name: 'ZINUS 12 Inch King Green Tea Memory Foam Mattress',
    category: 'Home & Kitchen',
    price: 319.99,
    originalPrice: 449.99,
    rating: 4.6,
    reviews: 28945,
    image: 'https://m.media-amazon.com/images/I/81XzXrlHljL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Zinus-Mattress-Fiberglass-Pressure-Certified/dp/B0CKZ1CK1H',
    description: 'Premium memory foam mattress infused with green tea extract for natural odor control and pressure relief',
    longDescription: 'Premium 12-inch memory foam mattress featuring green tea extract infusion for natural freshness and odor control. Multiple layers of foam provide superior pressure relief and support for a restful night\'s sleep.',
    features: ['Green tea infusion', '12-inch thickness', 'Pressure relieving foam', 'CertiPUR-US certified'],
    specs: { Size: 'King', Thickness: '12 inches', Material: 'Memory Foam', Certification: 'CertiPUR-US' }
  },
  {
    id: 9,
    name: 'Rubbermaid Brilliance Food Storage Containers',
    category: 'Home & Kitchen',
    price: 39.99,
    rating: 4.8,
    reviews: 45678,
    image: 'https://m.media-amazon.com/images/I/81Ap89R-ajL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Rubbermaid-Brilliance-Storage-Container-BPA-free/dp/B079M8FPTW',
    description: 'Crystal-clear BPA-free containers with leak-proof seals, perfect for meal prep and kitchen organization',
    longDescription: 'Premium food storage containers featuring crystal-clear Tritan material for easy visibility and 100% leak-proof seals. Microwave, dishwasher, and freezer safe for ultimate convenience in meal prep and storage.',
    features: ['100% leak-proof', 'Crystal-clear Tritan', 'Microwave & dishwasher safe', 'Modular stacking'],
    specs: { Material: 'BPA-free Tritan', Set: '10-piece', 'Seal Type': 'Leak-proof latch', Uses: 'Multi-purpose' }
  },
  {
    id: 10,
    name: 'Shark Upright Vacuum',
    category: 'Home & Kitchen',
    price: 199.99,
    rating: 4.7,
    reviews: 34567,
    image: 'https://m.media-amazon.com/images/I/71ybuaqVLwL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Shark-Navigator-Professional-Anti-Allergy-NV360/dp/B00JH98GR4',
    description: 'Professional upright vacuum with anti-allergy seal, HEPA filter, and swivel steering for easy maneuverability',
    longDescription: 'Professional upright vacuum with powerful suction and complete seal technology to trap dust and allergens. Features swivel steering for easy navigation around furniture and a lift-away canister for portable cleaning.',
    features: ['Anti-Allergy Complete Seal', 'HEPA filter', 'Swivel steering', 'Lift-Away technology'],
    specs: { Type: 'Upright', Filtration: 'HEPA', Capacity: '2.2 Quarts', Cord: '25 ft' }
  },

  // Beauty & Personal Care
  {
    id: 11,
    name: 'CeraVe Skin Renewing Night Cream',
    category: 'Beauty & Personal Care',
    price: 18.99,
    rating: 4.6,
    reviews: 23456,
    image: 'https://m.media-amazon.com/images/I/71r7bLsvaVL._SX466_.jpg',
    link: 'https://www.amazon.com/CeraVe-Skin-Renewing-Night-Cream/dp/B00SNPCSUY',
    description: 'Nourishing night cream with hyaluronic acid and peptide complex to restore skin while you sleep',
    longDescription: 'Nourishing night cream formulated with three essential ceramides, hyaluronic acid, and peptide complex to help restore and maintain the skin\'s natural protective barrier while you sleep. Non-comedogenic and fragrance-free.',
    features: ['3 essential ceramides', 'Hyaluronic acid', 'Peptide complex', 'Fragrance-free'],
    specs: { Size: '1.7 oz', Type: 'Night Cream', Skin: 'All types', Formula: 'Non-comedogenic' }
  },
  {
    id: 12,
    name: 'The Ordinary Hyaluronic Acid 2% + B5',
    category: 'Beauty & Personal Care',
    price: 8.99,
    rating: 4.5,
    reviews: 89234,
    image: 'https://m.media-amazon.com/images/I/61eH32lVpdL._SX522_.jpg',
    link: 'https://www.amazon.com/Ordinary-Hyaluronic-Acid-2-30ml/dp/B01MYEZPC8',
    description: 'Lightweight hydration serum with multiple weights of hyaluronic acid for deep moisture retention',
    longDescription: 'Lightweight water-based serum combining low, medium, and high molecular weight hyaluronic acid molecules along with a next-generation HA crosspolymer for multi-depth hydration. Enhanced with vitamin B5 for improved surface hydration.',
    features: ['Multi-weight hyaluronic acid', 'Vitamin B5', 'Lightweight texture', 'Deep hydration'],
    specs: { Size: '30ml', Type: 'Serum', Concentration: '2%', Vegan: 'Yes' }
  },
  {
    id: 13,
    name: 'LANEIGE Lip Sleeping Mask',
    category: 'Beauty & Personal Care',
    price: 24.00,
    rating: 4.7,
    reviews: 56789,
    image: 'https://m.media-amazon.com/images/I/51H5SkeGANL._SX522_.jpg',
    link: 'https://www.amazon.com/Laneige-Sleeping-Berry/dp/B07XXPHQZK',
    description: 'Overnight lip treatment with berry extract that intensely moisturizes and softens lips while you sleep',
    longDescription: 'Overnight lip treatment featuring Berry Mix Complex™ rich in antioxidants and Vitamin C. The balmy texture forms a protective film that locks in moisture and active ingredients for visibly smoother, more supple lips by morning.',
    features: ['Berry Mix Complex', 'Overnight moisture', 'Antioxidant-rich', 'Smooth texture'],
    specs: { Size: '20g', Type: 'Lip Mask', Flavor: 'Berry', Use: 'Overnight' }
  },
  {
    id: 14,
    name: 'Mielle Organics Rosemary & Mint Hair Oil',
    category: 'Beauty & Personal Care',
    price: 9.97,
    rating: 4.6,
    reviews: 34567,
    image: 'https://m.media-amazon.com/images/I/61n1krgI+tL._SX466_.jpg',
    link: 'https://www.amazon.com/Mielle-Rosemary-Mint-Scalp-Strengthening/dp/B07N7PK9QK',
    description: 'Nourishing scalp oil with biotin and rosemary to strengthen hair and promote healthy growth',
    longDescription: 'Nutrient-rich scalp and hair strengthening oil infused with biotin and over 30 essential oils including rosemary and mint. Helps improve circulation to the scalp, strengthens hair, and promotes a healthy scalp environment for optimal hair growth.',
    features: ['Biotin enriched', 'Rosemary & mint', '30+ essential oils', 'Scalp stimulation'],
    specs: { Size: '2 oz', Type: 'Hair Oil', Ingredients: 'Natural', Certified: 'Organic' }
  },
  {
    id: 15,
    name: "Hanes Men's Ecosmart Fleece Sweatshirt",
    category: 'Beauty & Personal Care',
    price: 12.00,
    rating: 4.5,
    reviews: 67890,
    image: 'https://m.media-amazon.com/images/I/81D+bCgn8hL._AC_SX569_.jpg',
    link: 'https://www.amazon.com/Hanes-EcoSmart-Fleece-Sweatshirt-Stonewashed/dp/B0721C21RJ',
    description: 'Classic crewneck sweatshirt made with eco-friendly fleece fabric for everyday comfort',
    longDescription: 'Classic crewneck sweatshirt made with EcoSmart fleece containing up to 5% recycled polyester from plastic bottles. Soft, medium-weight fabric provides warmth without bulk for comfortable everyday wear.',
    features: ['EcoSmart fleece', 'Ribbed cuffs', 'Pill-resistant', 'Tag-free'],
    specs: { Material: '50/50 Cotton/Poly', Fit: 'Regular', Weight: 'Medium', Eco: '5% Recycled' }
  },

  // Clothing, Shoes & Jewelry
  {
    id: 16,
    name: 'Hanes mens Zip-up Hoodie',
    category: 'Clothing, Shoes & Jewelry',
    price: 16.50,
    rating: 4.6,
    reviews: 45678,
    image: 'https://m.media-amazon.com/images/I/71QyRZzbaUL._AC_SX569_.jpg',
    link: 'https://www.amazon.com/Hanes-Full-zip-Eco-smart-athletic-sweatshirts/dp/B00JUM4CT4',
    description: 'Full-zip eco-smart hoodie with kangaroo pocket, perfect for layering and athletic activities',
    longDescription: 'Full-zip hoodie featuring EcoSmart fleece made with up to 5% recycled polyester. Full-length zipper allows for easy on/off and ventilation control. Kangaroo pocket provides convenient storage for essentials.',
    features: ['Full-zip design', 'Kangaroo pocket', 'EcoSmart fleece', 'Adjustable hood'],
    specs: { Material: '50/50 blend', Closure: 'Full-zip', Pockets: 'Kangaroo', Fit: 'Regular' }
  },
  {
    id: 17,
    name: 'adidas Mens Lite Racer Adapt 7.0 Shoes',
    category: 'Clothing, Shoes & Jewelry',
    price: 65.00,
    rating: 4.5,
    reviews: 12345,
    image: 'https://m.media-amazon.com/images/I/71JsiyZWwyL._AC_SY575_.jpg',
    link: 'https://www.amazon.com/adidas-Racer-Adapt-Sneaker-Black/dp/B0CKMC1BGB',
    description: 'Lightweight running-inspired sneakers with Cloudfoam cushioning for all-day comfort and style',
    longDescription: 'Running-inspired sneakers featuring a breathable mesh upper and Cloudfoam midsole for step-in comfort and superior cushioning. Slip-on design with elastic laces makes them easy to wear while maintaining a secure fit.',
    features: ['Cloudfoam cushioning', 'Mesh upper', 'Slip-on design', 'Flexible sole'],
    specs: { Brand: 'adidas', Type: 'Running shoe', Upper: 'Mesh', Sole: 'Rubber' }
  },
  {
    id: 18,
    name: "Levi's Men's 511 Slim Fit Jeans",
    category: 'Clothing, Shoes & Jewelry',
    price: 49.99,
    originalPrice: 69.50,
    rating: 4.6,
    reviews: 89012,
    image: 'https://m.media-amazon.com/images/I/81HRsNLuziL._AC_SX466_.jpg',
    link: 'https://www.amazon.com/Levis-Mens-Jeans-Stretch-Panda/dp/B072NGDWDY',
    description: 'Classic slim fit jeans with just the right amount of stretch for comfort and timeless style',
    longDescription: 'Iconic 511 Slim Fit jeans featuring a slim fit through the hip and thigh with a slightly tapered leg. Made with premium stretch denim for comfortable movement while maintaining the classic Levi\'s quality and style.',
    features: ['Slim fit', 'Stretch denim', 'Five-pocket styling', 'Zip fly'],
    specs: { Fit: 'Slim', Rise: 'Medium', Material: 'Stretch Denim', Closure: 'Zipper' }
  },
  {
    id: 19,
    name: 'Casio MDV106 Series',
    category: 'Clothing, Shoes & Jewelry',
    price: 59.95,
    rating: 4.7,
    reviews: 23456,
    image: 'https://m.media-amazon.com/images/I/61nHUVwR65L._AC_SY550_.jpg',
    link: 'https://www.amazon.com/Casio-MDV106-1AV-Analog-Watch-Black/dp/B009KYJAJY',
    description: 'Durable dive-style analog watch with 200m water resistance and reliable quartz movement',
    longDescription: 'Professional dive-style analog watch featuring 200-meter water resistance, unidirectional rotating bezel, and luminous hands and markers for underwater visibility. Durable resin band and reliable Japanese quartz movement.',
    features: ['200m water resistant', 'Rotating bezel', 'Luminous markers', 'Quartz movement'],
    specs: { Movement: 'Quartz', 'Water Resistance': '200m', Display: 'Analog', Band: 'Resin' }
  },
  {
    id: 20,
    name: "Fossil Women's Fiona Large Crossbody Purse",
    category: 'Clothing, Shoes & Jewelry',
    price: 98.00,
    originalPrice: 128.00,
    rating: 4.6,
    reviews: 5678,
    image: 'https://m.media-amazon.com/images/I/81H9ZCTU4wL._AC_SY575_.jpg',
    link: 'https://www.amazon.com/Fossil-Fiona-EW-Crossbody-Brown/dp/B07DLMZ4C7',
    description: 'Elegant leather crossbody handbag with adjustable strap and multiple compartments for organization',
    longDescription: 'Sophisticated crossbody handbag crafted from quality leather with multiple interior pockets and card slots for organized storage. Adjustable strap allows for comfortable wear as crossbody or shoulder bag.',
    features: ['Genuine leather', 'Adjustable strap', 'Multiple pockets', 'Zip closure'],
    specs: { Material: 'Leather', Size: 'Large', Strap: 'Adjustable', Closure: 'Zipper' }
  },

  // Toys & Games
  {
    id: 21,
    name: 'LEGO Classic Medium Creative Brick Box 10696',
    category: 'Toys & Games',
    price: 39.99,
    rating: 4.9,
    reviews: 78901,
    image: 'https://m.media-amazon.com/images/I/8160QjpuoOL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/LEGO-Classic-Medium-Creative-Brick/dp/B00NHQFA1I',
    description: 'Creative building set with 484 colorful pieces to inspire endless imagination and construction fun',
    longDescription: 'Creative building set featuring 484 pieces in 35 different colors for endless building possibilities. Includes windows, eyes, and wheels plus a building ideas booklet to inspire creativity and imagination.',
    features: ['484 pieces', '35 colors', 'Building ideas included', 'Classic LEGO bricks'],
    specs: { Pieces: 484, Ages: '4+', Theme: 'Classic', Type: 'Building Set' }
  },
  {
    id: 22,
    name: 'Mattel Games UNO Teams Card Game',
    category: 'Toys & Games',
    price: 9.99,
    rating: 4.7,
    reviews: 12345,
    image: 'https://m.media-amazon.com/images/I/91zZyNjPcLL._AC_SY879_.jpg',
    link: 'https://www.amazon.com/Mattel-Games-Adults-Parties-Special/dp/B0D6X9T62X',
    description: 'Classic card game with a team twist, perfect for family game nights and social gatherings',
    longDescription: 'Classic UNO game with a team play twist that adds a new level of strategy and excitement. Players work together with their teammate to be the first team to get rid of all their cards. Perfect for 4+ players.',
    features: ['Team gameplay', '4+ players', 'Quick setup', 'Travel-friendly'],
    specs: { Players: '4+', Ages: '7+', 'Play Time': '30 min', Cards: '112' }
  },
  {
    id: 23,
    name: 'Barbie Dreamhouse',
    category: 'Toys & Games',
    price: 199.99,
    originalPrice: 249.99,
    rating: 4.8,
    reviews: 34567,
    image: 'https://m.media-amazon.com/images/I/71PFKADv6CL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Barbie-Dreamhouse-3-Story-Playset-Elevator/dp/B0BLJTJ38M',
    description: '3-story dollhouse with working elevator, pool, slide, and 75+ accessories for imaginative play',
    longDescription: 'Iconic 3-story Dreamhouse featuring 8 rooms, a working elevator, pool with slide, and 75+ accessories. Interactive features include lights, sounds, and transformation play pieces for endless storytelling possibilities.',
    features: ['3 stories, 8 rooms', 'Working elevator', 'Pool with slide', '75+ accessories'],
    specs: { Height: '3.75 feet', Rooms: '8', Features: 'Lights & sounds', Ages: '3+' }
  },
  {
    id: 24,
    name: 'Nintendo Switch 2 + Mario Kart World Bundle',
    category: 'Toys & Games',
    price: 359.99,
    rating: 4.9,
    reviews: 23456,
    image: 'https://m.media-amazon.com/images/I/715AHrLja3L._SX522_.jpg',
    link: 'https://www.amazon.com/Nintendo-Switch-Mario-World-Bundle-2/dp/B0FC5FJZ9Z',
    description: 'Next-gen gaming console bundle with Mario Kart World for portable and TV play experiences',
    longDescription: 'Next-generation Switch console with enhanced graphics and performance. Bundle includes Mario Kart World game. Play on TV at home or take it on the go for portable gaming experiences.',
    features: ['Portable & TV mode', 'Enhanced graphics', 'Mario Kart included', 'Multiplayer ready'],
    specs: { Screen: '7" OLED', Storage: '64GB', Battery: '9 hours', Controllers: '2 Joy-Cons' }
  },
  {
    id: 25,
    name: 'Play-Doh Modeling Compound 10-Pack',
    category: 'Toys & Games',
    price: 9.97,
    rating: 4.8,
    reviews: 67890,
    image: 'https://m.media-amazon.com/images/I/71LqxbA1WCL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Play-Doh-Modeling-Compound-Non-Toxic-Exclusive/dp/B00JM5GW10',
    description: 'Non-toxic modeling compound in 10 vibrant colors for endless creative sculpting and artistic fun',
    longDescription: 'Classic modeling compound in 10 different vibrant colors. Non-toxic formula is safe for creative play. Each can contains 2 ounces of soft, pliable compound perfect for molding, sculpting, and imaginative creations.',
    features: ['10 vibrant colors', 'Non-toxic formula', '2 oz per can', 'Soft & pliable'],
    specs: { Colors: '10', Amount: '20 oz total', Ages: '2+', Safe: 'Non-toxic' }
  },

  // Health & Household / Baby
  {
    id: 26,
    name: 'Pampers Sensitive Baby Wipes',
    category: 'Health & Household / Baby',
    price: 24.97,
    rating: 4.8,
    reviews: 123456,
    image: 'https://m.media-amazon.com/images/I/71NqHkGRN1L._AC_SX679_PIbundle-12,TopRight,0,0_SH20_.jpg',
    link: 'https://www.amazon.com/Pampers-Wipes-Sensitive-Perfume-Multi/dp/B0BJ13K7FR',
    description: 'Hypoallergenic and perfume-free baby wipes with clinically proven mild formula for sensitive skin',
    longDescription: 'Hypoallergenic and perfume-free baby wipes with a clinically proven mild formula. Thick and gentle, these wipes are perfect for sensitive skin and provide a thorough clean with every wipe.',
    features: ['Hypoallergenic', 'Perfume-free', 'Clinically proven mild', 'Thick & gentle'],
    specs: { Count: '12 packs', 'Per Pack': '56 wipes', Total: '672 wipes', pH: 'Balanced' }
  },
  {
    id: 27,
    name: 'Charmin Ultra Soft Cushiony Touch Toilet Paper',
    category: 'Health & Household / Baby',
    price: 36.94,
    rating: 4.8,
    reviews: 89012,
    image: 'https://m.media-amazon.com/images/I/81Xyre0z0VL._AC_SX679_PIbundle-24,TopRight,0,0_SH20_.jpg',
    link: 'https://www.amazon.com/Charmin-Toilet-Family-Cushiony-Sheets/dp/B0798DVT68',
    description: 'Luxuriously soft and absorbent toilet tissue with cushiony texture for ultimate comfort',
    longDescription: 'Luxuriously soft and absorbent 2-ply toilet paper with Charmin\'s signature cushiony texture. Septic-safe and clog-safe when used as directed. Each Family Mega Roll has 264 sheets.',
    features: ['2-ply softness', 'Cushiony texture', 'Septic-safe', 'Clog-safe'],
    specs: { Rolls: '24 Family Mega', 'Sheets per Roll': 264, Ply: '2-ply', Safe: 'Septic-safe' }
  },
  {
    id: 28,
    name: "Nature's Way Sambucus Elderberry Gummies",
    category: 'Health & Household / Baby',
    price: 14.99,
    rating: 4.6,
    reviews: 45678,
    image: 'https://m.media-amazon.com/images/I/7134HKzZjdL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Natures-Way-Elderberry-Vegetarian-Packaging/dp/B00MJ7VL1O',
    description: 'Vegetarian elderberry gummies with vitamin C and zinc to support immune health for the whole family',
    longDescription: 'Delicious vegetarian gummies made with premium black elderberry extract plus vitamin C and zinc for immune support. Great tasting and pectin-based formula suitable for the whole family.',
    features: ['Black elderberry', 'Vitamin C & Zinc', 'Vegetarian', 'Great taste'],
    specs: { Count: '60 gummies', Servings: '30', Type: 'Gummy', Vegetarian: 'Yes' }
  },
  {
    id: 29,
    name: 'Huggies Natural Care Sensitive Baby Wipes',
    category: 'Health & Household / Baby',
    price: 22.97,
    rating: 4.8,
    reviews: 98765,
    image: 'https://m.media-amazon.com/images/I/81FlNgJOeqL._AC_SX679_PIbundle-12,TopRight,0,0_SH20_.jpg',
    link: 'https://www.amazon.com/HUGGIES-Natural-Unscented-Sensitive-Water-Based/dp/B07SCL613T',
    description: 'Water-based unscented baby wipes with gentle plant-derived ingredients for delicate skin care',
    longDescription: 'Water-based baby wipes made with 99% purified water and gentle plant-derived ingredients. Unscented and hypoallergenic formula is clinically proven gentle for sensitive skin. Thick and absorbent.',
    features: ['99% water', 'Plant-derived', 'Unscented', 'Hypoallergenic'],
    specs: { Packs: '12', 'Per Pack': '56 wipes', Total: '672 wipes', Base: 'Water' }
  },
  {
    id: 30,
    name: 'Philips Avent Natural Glass Baby Bottles',
    category: 'Health & Household / Baby',
    price: 29.99,
    rating: 4.7,
    reviews: 12345,
    image: 'https://m.media-amazon.com/images/I/71IsWBuTvfL._SX466_.jpg',
    link: 'https://www.amazon.com/Philips-Natural-Response-SCY910-04/dp/B098YHHV3Q',
    description: 'Premium glass bottles with Natural Response nipples designed to mimic breastfeeding for easy feeding',
    longDescription: 'Premium glass baby bottles featuring Natural Response nipples with an innovative opening that releases milk only when baby actively drinks. Glass material is easy to clean and naturally BPA-free.',
    features: ['Natural Response nipple', 'Glass material', 'Anti-colic', 'BPA-free'],
    specs: { Material: 'Glass', Size: '8 oz', Count: '4 bottles', Nipple: 'Natural Response' }
  },

  // Sports & Outdoors
  {
    id: 31,
    name: 'Fitbit Charge 6 Fitness Tracker',
    category: 'Sports & Outdoors',
    price: 159.95,
    originalPrice: 199.95,
    rating: 4.5,
    reviews: 23456,
    image: 'https://m.media-amazon.com/images/I/61ZtqtvoD2L._AC_SX466_.jpg',
    link: 'https://www.amazon.com/Fitbit-Exercise-Equipment-6-Months-Membership/dp/B0CC62ZG1M',
    description: 'Advanced fitness tracker with Google apps integration, heart rate monitoring, and built-in GPS',
    longDescription: 'Advanced fitness tracker with built-in GPS, 24/7 heart rate monitoring, and Google apps integration. Track workouts, sleep, stress, and more. Includes 6-month Fitbit Premium membership.',
    features: ['Built-in GPS', 'Heart rate monitoring', 'Google apps', '40+ exercise modes'],
    specs: { Display: 'AMOLED', Battery: '7 days', 'Water Resistance': '50m', Connectivity: 'Bluetooth' }
  },
  {
    id: 32,
    name: 'Coleman Sundome Camping Tent with Rainfly',
    category: 'Sports & Outdoors',
    price: 89.99,
    rating: 4.6,
    reviews: 34567,
    image: 'https://m.media-amazon.com/images/I/61aUr3tBexL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Coleman-Weatherproof-Festivals-Backyard-Sleepovers/dp/B0D7QLQNS5',
    description: 'Weatherproof dome tent with easy setup, ideal for camping trips, festivals, and outdoor adventures',
    longDescription: 'Weatherproof dome tent featuring WeatherTec system with patented welded floors and inverted seams to keep water out. Easy setup with snag-free Insta-Clip pole attachments. Fits 2-4 people.',
    features: ['WeatherTec system', 'Easy setup', 'Vented windows', 'E-port for power'],
    specs: { Capacity: '4 person', Size: '8x7 ft', Height: '4.5 ft', Setup: 'Quick' }
  },
  {
    id: 33,
    name: "Under Armour Men's Charged Assert 10 Shoes",
    category: 'Sports & Outdoors',
    price: 65.00,
    rating: 4.5,
    reviews: 12345,
    image: 'https://m.media-amazon.com/images/I/61O30g0cZmL._AC_SY575_.jpg',
    link: 'https://www.amazon.com/Under-Armour-Charged-Assert-Running/dp/B09XBWQ9Y9',
    description: 'Versatile running shoes with Charged Cushioning for responsive comfort and support during workouts',
    longDescription: 'Versatile running shoes featuring Charged Cushioning midsole for responsive comfort and support. Lightweight mesh upper provides breathability, while durable leather overlays add stability and structure.',
    features: ['Charged Cushioning', 'Mesh upper', 'Durable overlays', 'Flexible sole'],
    specs: { Type: 'Running', Cushioning: 'Charged', Upper: 'Mesh & Leather', Sole: 'Rubber' }
  },
  {
    id: 34,
    name: 'Garmin Forerunner 55',
    category: 'Sports & Outdoors',
    price: 199.99,
    rating: 4.7,
    reviews: 23456,
    image: 'https://m.media-amazon.com/images/I/518z0My1ZlS._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Garmin-Forerunner-Running-Suggested-Workouts/dp/B092RCLKHN',
    description: 'GPS running watch with suggested workouts, pace guidance, and comprehensive health monitoring features',
    longDescription: 'Easy-to-use GPS running watch with suggested workouts based on your training history and fitness level. Features PacePro pacing guidance, running dynamics, and all-day health monitoring including heart rate and stress.',
    features: ['Built-in GPS', 'Suggested workouts', 'PacePro guidance', 'Health monitoring'],
    specs: { Display: 'Sunlight-readable', Battery: '2 weeks', GPS: 'Built-in', 'Water Rating': '5 ATM' }
  },
  {
    id: 35,
    name: 'YETI Rambler 20 oz Travel Mug',
    category: 'Sports & Outdoors',
    price: 38.00,
    rating: 4.8,
    reviews: 45678,
    image: 'https://m.media-amazon.com/images/I/51kXewLNVGL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/YETI-Rambler-Stainless-Insulated-MagSlider/dp/B08D3VPRQ1',
    description: 'Durable stainless steel insulated mug with MagSlider lid to keep drinks hot or cold for hours',
    longDescription: 'Durable travel mug with double-wall vacuum insulation to keep drinks hot or cold for hours. Features MagSlider lid for easy opening and closing, plus a durable handle for convenient carrying. Dishwasher safe.',
    features: ['Double-wall insulated', 'MagSlider lid', 'Durable handle', 'Dishwasher safe'],
    specs: { Capacity: '20 oz', Material: 'Stainless Steel', Insulation: 'Vacuum', Handle: 'Yes' }
  },

  // Books
  {
    id: 36,
    name: 'Atomic Habits by James Clear',
    category: 'Books',
    price: 27.00,
    originalPrice: 32.00,
    rating: 4.9,
    reviews: 156789,
    image: 'https://m.media-amazon.com/images/I/71F4+7rk2eL._SX342_.jpg',
    link: 'https://www.amazon.com/Atomic-Habits-James-Clear-audiobook/dp/B07RFSSYBH',
    description: 'Practical guide to building good habits and breaking bad ones with proven strategies and real-world examples',
    longDescription: 'Practical guide revealing how tiny changes can lead to remarkable results. Learn proven strategies to build good habits, break bad ones, and master the tiny behaviors that lead to remarkable outcomes.',
    features: ['Habit formation', 'Behavior change', 'Practical strategies', 'Real examples'],
    specs: { Author: 'James Clear', Pages: '320', Format: 'Hardcover', Publisher: 'Avery' }
  },
  {
    id: 37,
    name: "The Subtle Art of Not Giving a F*ck",
    category: 'Books',
    price: 25.00,
    rating: 4.6,
    reviews: 98765,
    image: 'https://m.media-amazon.com/images/I/81A5jQHA+lL._SX342_.jpg',
    link: 'https://www.amazon.com/Subtle-Art-Not-Giving-Counterintuitive/dp/B01I29Y344',
    description: 'Counterintuitive self-help book about embracing life\'s limitations and choosing what truly matters',
    longDescription: 'Counterintuitive approach to living a good life that challenges the conventional wisdom of positive thinking. Learn to embrace life\'s limitations and focus your energy on what truly matters.',
    features: ['Counterintuitive wisdom', 'Life philosophy', 'Real talk', 'Practical advice'],
    specs: { Author: 'Mark Manson', Pages: '224', Format: 'Paperback', Language: 'English' }
  },
  {
    id: 38,
    name: "Harry Potter and the Sorcerer's Stone",
    category: 'Books',
    price: 29.99,
    rating: 4.9,
    reviews: 234567,
    image: 'https://m.media-amazon.com/images/I/91eopoUCjLL._SX342_.jpg',
    link: 'https://www.amazon.com/Harry-Potter-Sorcerers-Stone-Book/dp/B017V4IMVQ',
    description: 'Magical beginning of the beloved series following young wizard Harry Potter\'s adventures at Hogwarts',
    longDescription: 'Magical beginning of the beloved series following orphan Harry Potter who discovers he\'s a wizard on his 11th birthday. Join Harry as he attends Hogwarts School of Witchcraft and Wizardry and uncovers his extraordinary destiny.',
    features: ['Fantasy adventure', 'Coming of age', 'Magic & friendship', 'Series starter'],
    specs: { Author: 'J.K. Rowling', Pages: '309', Series: 'Book 1 of 7', Format: 'Hardcover' }
  },
  {
    id: 39,
    name: '48 Laws of Power',
    category: 'Books',
    price: 32.00,
    rating: 4.7,
    reviews: 67890,
    image: 'https://m.media-amazon.com/images/I/71s-d6iLlaL._SX342_.jpg',
    link: 'https://www.amazon.com/48-Laws-of-Power-Robert-Greene-audiobook/dp/B00X0TKUS0',
    description: 'Timeless guide to understanding and mastering power dynamics in business, politics, and everyday life',
    longDescription: 'Timeless guide distilling 3,000 years of power dynamics into 48 laws. Learn to navigate complex social situations, understand manipulation tactics, and master the subtle art of power in all aspects of life.',
    features: ['Power dynamics', 'Strategic thinking', 'Historical examples', 'Practical laws'],
    specs: { Author: 'Robert Greene', Pages: '452', Format: 'Paperback', Genre: 'Self-help' }
  },
  {
    id: 40,
    name: 'Furbo 360° Dog Camera',
    category: 'Pet Supplies',
    price: 209.99,
    originalPrice: 249.99,
    rating: 4.5,
    reviews: 12345,
    image: 'https://m.media-amazon.com/images/I/616wRFOTA5L._AC_SX466_.jpg',
    link: 'https://www.amazon.com/Furbo-Camera-with-360%C2%B0-View/dp/B09GDQZLD1',
    description: '360-degree pet camera with treat tossing, barking alerts, and two-way audio to stay connected with your dog',
    longDescription: '360-degree rotating pet camera with treat tossing capability, barking alerts, and two-way audio. Features Full HD video, night vision, and smart dog alerts to keep you connected with your furry friend from anywhere.',
    features: ['360° rotation', 'Treat tossing', 'Two-way audio', 'Barking alerts', 'Night vision'],
    specs: { Resolution: '1080p', Rotation: '360 degrees', Audio: '2-way', Connectivity: 'Wi-Fi' }
  },

  // Garden & Tools
  {
    id: 41,
    name: 'Weber Spirit E-310 Gas Grill',
    category: 'Garden & Tools',
    price: 549.00,
    originalPrice: 599.00,
    rating: 4.7,
    reviews: 23456,
    image: 'https://m.media-amazon.com/images/I/71vd9uEPNFL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Weber-SPIRIT-3-Burner-Liquid-Propane/dp/B0DPH6NNTB',
    description: '3-burner liquid propane gas grill with porcelain-enameled lid and cooking grates for perfect outdoor BBQ',
    longDescription: '3-burner liquid propane gas grill with porcelain-enameled lid and cooking grates for perfect outdoor BBQ. Features 529 square inches of cooking space, powerful GS4 grilling system, and durable construction.',
    features: ['3 stainless steel burners', 'Porcelain-enameled cast iron grates', 'Built-in thermometer', 'Side tables for prep'],
    specs: { Fuel: 'Liquid Propane', Burners: '3', 'Cooking Area': '529 sq in', Material: 'Stainless Steel' }
  },
  {
    id: 42,
    name: 'Gardening Tools 9-Piece',
    category: 'Garden & Tools',
    rating: 4.6,
    reviews: 8543,
    image: 'https://m.media-amazon.com/images/I/81hk0PGpklL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/dp/B09F9C3KFS',
    description: 'Complete 9-piece gardening tool set with ergonomic handles for all your planting and maintenance needs',
    longDescription: 'Complete 9-piece gardening tool set including trowel, transplanter, cultivator, weeder, pruner, and more. Ergonomic soft-grip handles reduce hand strain while durable stainless steel heads resist rust and wear.',
    features: ['9 essential tools', 'Ergonomic handles', 'Stainless steel', 'Storage bag included'],
    specs: { Pieces: '9', Material: 'Stainless Steel', Handles: 'Soft-grip', Includes: 'Storage bag' }
  },
  {
    id: 43,
    name: 'Gardening Tool Set, CHRYZTAL',
    category: 'Garden & Tools',
    rating: 4.7,
    reviews: 12234,
    image: 'https://m.media-amazon.com/images/I/71UDfsaOKvL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/dp/B09F3CWRRC',
    description: 'Premium gardening tool collection with durable construction and comfortable grips for garden enthusiasts',
    longDescription: 'Premium gardening tool collection featuring heavy-duty cast-aluminum heads and comfortable rubberized grips. Set includes all essential tools for digging, weeding, pruning, and transplanting with professional-grade quality.',
    features: ['Cast-aluminum heads', 'Rubberized grips', 'Professional grade', 'Complete set'],
    specs: { Material: 'Cast Aluminum', Grip: 'Rubberized', Quality: 'Professional', Warranty: '1 year' }
  },
  {
    id: 44,
    name: 'HomGarden Folding Garden Kneeler Seat Bench Stool',
    category: 'Garden & Tools',
    rating: 4.5,
    reviews: 15678,
    image: 'https://m.media-amazon.com/images/I/71CZ9FyVBhL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/dp/B07J66MY3Y',
    description: 'Versatile folding garden seat and kneeler with tool pouch to reduce strain while gardening',
    longDescription: 'Versatile 2-in-1 folding garden kneeler and seat reduces back and knee strain while gardening. Features thick EVA foam pad, sturdy steel frame, two tool pouches, and folds flat for easy storage.',
    features: ['2-in-1 design', 'EVA foam pad', 'Tool pouches', 'Folds flat'],
    specs: { Weight: 'Capacity 330 lbs', Frame: 'Steel', Pad: 'EVA foam', Folding: 'Yes' }
  },
  {
    id: 45,
    name: 'Garden Flat Shovel - Snow Ice Scraper',
    category: 'Garden & Tools',
    rating: 4.4,
    reviews: 6789,
    image: 'https://m.media-amazon.com/images/I/81IY7R7mHfL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/dp/B0DBZM45GP',
    description: 'Multi-purpose flat shovel ideal for gardening, snow removal, and ice scraping tasks',
    longDescription: 'Multi-purpose flat shovel with durable steel blade and comfortable D-grip handle. Perfect for edging gardens, moving soil, clearing snow, and scraping ice. Powder-coated finish prevents rust.',
    features: ['Steel blade', 'D-grip handle', 'Multi-purpose', 'Rust-resistant'],
    specs: { Blade: 'Steel', Length: '48 inches', Handle: 'D-grip', Coating: 'Powder-coat' }
  },
  {
    id: 46,
    name: 'Kurapika Patio Furniture Set 4 Pieces',
    category: 'Garden & Tools',
    rating: 4.3,
    reviews: 8934,
    image: 'https://m.media-amazon.com/images/I/71ZBHo8TceL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Kurapika-Furniture-Outdoor-Conversation-Backyard/dp/B0DP43X8ZJ',
    description: 'Stylish 4-piece outdoor conversation set perfect for backyard gatherings and patio relaxation',
    longDescription: 'Stylish 4-piece outdoor furniture set including 2 single chairs, 1 loveseat, and coffee table. Weather-resistant PE rattan and powder-coated steel frame with thick cushions for comfort.',
    features: ['4-piece set', 'Weather-resistant', 'Thick cushions', 'Steel frame'],
    specs: { Pieces: '4', Material: 'PE Rattan', Frame: 'Steel', Cushions: 'Included' }
  },
  {
    id: 47,
    name: 'Devoko Patio Porch Furniture Sets 3 Pieces',
    category: 'Garden & Tools',
    rating: 4.6,
    reviews: 23456,
    image: 'https://m.media-amazon.com/images/I/81VhMt7V08L._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Devoko-Furniture-Rattan-Cushion-Outdoor/dp/B0765VTBLV',
    description: 'Comfortable rattan patio furniture set with cushions for outdoor lounging and entertaining',
    longDescription: 'Comfortable 3-piece rattan patio furniture set with premium cushions. Includes 2 chairs and 1 table. Durable hand-woven PE rattan over sturdy steel frame. Water-resistant cushion covers.',
    features: ['Hand-woven rattan', 'Premium cushions', '3-piece set', 'Water-resistant covers'],
    specs: { Pieces: '3', Weave: 'Hand-woven PE', Frame: 'Steel', Covers: 'Water-resistant' }
  },
  {
    id: 48,
    name: '3 Pieces Outdoor Patio Furniture Set',
    category: 'Garden & Tools',
    rating: 4.5,
    reviews: 11234,
    image: 'https://m.media-amazon.com/images/I/71tXTDVLrFL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Qsun-Furniture-Conversation-Backyard-Poolside/dp/B09CDNXK56',
    description: 'Compact 3-piece patio set ideal for backyard, poolside, or balcony conversation areas',
    longDescription: 'Compact 3-piece bistro set perfect for small spaces including balconies, patios, and poolside areas. Features 2 comfortable chairs and 1 side table. Weather-resistant construction for year-round use.',
    features: ['Compact design', '2 chairs + table', 'Weather-resistant', 'Small space friendly'],
    specs: { Pieces: '3', Style: 'Bistro', 'Space Type': 'Small', Weather: 'Resistant' }
  },
  {
    id: 49,
    name: 'Mouse Station with Keys',
    category: 'Garden & Tools',
    rating: 4.4,
    reviews: 9876,
    image: 'https://m.media-amazon.com/images/I/61Xjhe-7-1L._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Mouse-Station-Keys-Required-Stations/dp/B0FDFHPVQ7',
    description: 'Professional mouse control station with secure key access for safe rodent management',
    longDescription: 'Professional tamper-resistant mouse bait station with secure key-access system for safe pest control around homes, gardens, and outbuildings. Protects children and pets while effectively managing rodent problems.',
    features: ['Key-access security', 'Tamper-resistant', 'Weather-proof', 'Refillable'],
    specs: { Type: 'Bait Station', Access: 'Key-locked', Use: 'Indoor/Outdoor', Material: 'Durable plastic' }
  },
  {
    id: 50,
    name: 'JAMFLY Egg Chair Wicker Outdoor Chairs',
    category: 'Garden & Tools',
    rating: 4.7,
    reviews: 3456,
    image: 'https://m.media-amazon.com/images/I/71ekHPtCxdL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/JAMFLY-Outdoor-Oversized-Lounger-Backyard/dp/B0D11DZZ5J',
    description: 'Oversized wicker egg chair lounger perfect for backyard relaxation and outdoor comfort',
    longDescription: 'Oversized wicker egg chair with sturdy steel stand and thick cushions creates a luxurious outdoor relaxation spot. Weather-resistant PE wicker construction perfect for patios, decks, and gardens.',
    features: ['Oversized design', 'Steel stand included', 'Thick cushions', 'Weather-resistant wicker'],
    specs: { Weight: 'Capacity 300 lbs', Material: 'PE Wicker', Stand: 'Steel', Cushion: 'Removable' }
  },

  // Pet Supplies (continued)
  {
    id: 51,
    name: 'Amazon Basics Dog and Puppy Pee Pads',
    category: 'Pet Supplies',
    rating: 4.6,
    reviews: 87543,
    image: 'https://m.media-amazon.com/images/I/71LHksRF15L._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Amazon-Basics-Heavy-Duty-Absorbency-Regular/dp/B00MW8G62E',
    description: 'Heavy-duty absorbent training pads with 5-layer leak-proof design, perfect for puppy training and senior dogs',
    longDescription: 'Heavy-duty absorbent training pads with 5-layer leak-proof design including quick-dry surface and built-in attractant. Perfect for puppy training, senior dogs, or pets with special needs.',
    features: ['5-layer protection', 'Leak-proof backing', 'Quick-dry surface', 'Built-in attractant'],
    specs: { Size: '22 x 22 inches', Quantity: '100 count', Absorbency: 'Heavy-duty', Type: 'Disposable' }
  },
  {
    id: 52,
    name: 'PetSafe ScoopFree Purple Front-Entry Uncovered Ultra Self Cleaning Cat Litter Box System',
    category: 'Pet Supplies',
    rating: 4.3,
    reviews: 12456,
    image: 'https://m.media-amazon.com/images/I/71BRBQMSoBL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/PetSafe-ScoopFree-Litter-Tray-Refills/dp/B000ELUQQS',
    description: 'Automatic self-cleaning litter box with crystal litter that absorbs odors, reduces tracking, and lasts weeks',
    longDescription: 'Automatic self-cleaning litter box with rake system that automatically removes waste 20 minutes after use. Crystal litter absorbs odors and reduces tracking. Front-entry design is comfortable for cats.',
    features: ['Automatic cleaning', 'Crystal litter', 'Front-entry', 'Odor control'],
    specs: { Type: 'Self-cleaning', Litter: 'Crystal', Entry: 'Front', Power: 'AC adapter' }
  },
  {
    id: 53,
    name: 'PetSafe Gentle Leader No-Pull Headcollar',
    category: 'Pet Supplies',
    rating: 4.2,
    reviews: 34567,
    image: 'https://m.media-amazon.com/images/I/61mGDGV7V-L._AC_SX679_.jpg',
    link: 'https://www.amazon.com/PetSafe-Gentle-Leader-Headcollar-Training/dp/B00074L4W2',
    description: 'Veterinarian-recommended headcollar that gently stops pulling and jumping, makes walks more enjoyable',
    longDescription: 'Veterinarian-recommended headcollar that works with your dog\'s natural instincts to gently reduce pulling, jumping, and lunging. Fits around the neck and nose for better control without choking.',
    features: ['Veterinarian recommended', 'Stops pulling', 'Gentle control', 'Easy to use'],
    specs: { Type: 'Headcollar', Sizes: 'Multiple', Material: 'Nylon', Recommended: 'Vet-approved' }
  },
  {
    id: 54,
    name: 'Hill\'s Science Diet Indoor',
    category: 'Pet Supplies',
    rating: 4.7,
    reviews: 45678,
    image: 'https://m.media-amazon.com/images/I/81gu7OG9-4L._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Hills-Science-Diet-Adult-Chicken/dp/B003MA8P02',
    description: 'Premium indoor cat food with natural fiber for healthy digestion and hairball control, made with real chicken',
    longDescription: 'Premium indoor cat food formulated specifically for adult cats living indoors. Made with real chicken and natural fiber for healthy digestion and hairball control. Balanced nutrition for optimal weight.',
    features: ['Real chicken', 'Natural fiber', 'Hairball control', 'Weight management'],
    specs: { Formula: 'Indoor Adult', Protein: 'Chicken', Fiber: 'Natural', Size: '15.5 lbs' }
  },
  {
    id: 55,
    name: 'HONEY CARE All-Absorb A26 Male Dog Wrap',
    category: 'Pet Supplies',
    rating: 4.5,
    reviews: 23456,
    image: 'https://m.media-amazon.com/images/I/71gYlXY6i-L._AC_SX679_.jpg',
    link: 'https://www.amazon.com/All-Absorb-Male-Dog-Wrap-Count/dp/B07C22NTL4',
    description: 'Disposable male dog wraps with leak-proof barriers and wetness indicator, perfect for marking and incontinence',
    longDescription: 'Disposable male dog wraps with super-absorbent core, leak-proof barriers, and wetness indicator. Perfect solution for male dogs with marking, incontinence, or excitable urination issues.',
    features: ['Super-absorbent', 'Leak-proof', 'Wetness indicator', 'Adjustable fit'],
    specs: { Type: 'Male wrap', Count: '50', Sizes: 'Multiple', Indicator: 'Wetness' }
  },
  {
    id: 56,
    name: 'Rocco & Roxie Supply Co. Stain & Strong Odor Eliminator',
    category: 'Pet Supplies',
    rating: 4.6,
    reviews: 98765,
    image: 'https://m.media-amazon.com/images/I/71RbenYSqsL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Rocco-Roxie-Supply-Co-Professional/dp/B00CKFL93K',
    description: 'Professional strength enzyme cleaner that eliminates pet stains and odors from carpets, furniture, and floors',
    longDescription: 'Professional strength enzyme cleaner that completely removes pet stains and odors from carpets, furniture, and floors. Safe for use around pets and children. Certified gentle and non-toxic.',
    features: ['Enzyme formula', 'Removes odors completely', 'Safe & non-toxic', 'Multi-surface'],
    specs: { Size: '32 oz', Type: 'Enzyme cleaner', Safe: 'Pet & child', Uses: 'Multi-surface' }
  },
  {
    id: 57,
    name: 'Pur Luv Chicken Jerky Dog Treats',
    category: 'Pet Supplies',
    rating: 4.5,
    reviews: 12345,
    image: 'https://m.media-amazon.com/images/I/816d5YD4e9L._AC_SY879_.jpg',
    link: 'https://www.amazon.com/Pur-Luv-Chicken-Jerky-Treats/dp/B08P2D95G8',
    description: 'Premium chicken jerky strips made with real chicken, no artificial flavors, perfect training treats for dogs',
    longDescription: 'Premium chicken jerky strips made with real chicken breast and no artificial flavors, colors, or preservatives. Soft and chewy texture perfect for training or rewarding your dog.',
    features: ['Real chicken', 'No artificial ingredients', 'Soft & chewy', 'Training size'],
    specs: { Flavor: 'Chicken', Size: 'Training strips', Weight: '32 oz', Artificial: 'None' }
  },
  {
    id: 58,
    name: 'Milk-Bone Mini\'s Flavor Snacks Dog Treats',
    category: 'Pet Supplies',
    rating: 4.7,
    reviews: 67890,
    image: 'https://m.media-amazon.com/images/I/81tU7UkyxZL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Milk-Bone-Flavor-Snacks-Biscuits-36-Ounce/dp/B0114BNXQ6',
    description: 'Classic mini biscuits in 3 delicious flavors with vitamins and minerals for strong bones and healthy teeth',
    longDescription: 'Classic mini dog biscuits in 3 delicious flavors with 12 vitamins and minerals. Crunchy texture helps clean teeth and freshen breath. Perfect size for small dogs or training treats.',
    features: ['3 flavors', '12 vitamins & minerals', 'Cleans teeth', 'Mini size'],
    specs: { Size: 'Mini', Flavors: '3 varieties', Weight: '36 oz', Benefits: 'Dental' }
  },
  {
    id: 59,
    name: 'INABA Churu Cat Treats',
    category: 'Pet Supplies',
    rating: 4.8,
    reviews: 54321,
    image: 'https://m.media-amazon.com/images/I/71B8D1hWW4L._AC_SX679_.jpg',
    link: 'https://www.amazon.com/INABA-Chicken-Lickable-Creamy-Variety/dp/B07D323MFZ',
    description: 'Lickable creamy puree treats for cats with farm-raised chicken, grain-free and low calorie, cats go crazy for these',
    longDescription: 'Lickable creamy puree treats made with farm-raised chicken and natural ingredients. Grain-free, preservative-free, and low in calories. Cats love the irresistible texture and flavor.',
    features: ['Lickable puree', 'Farm-raised chicken', 'Grain-free', 'Low calorie'],
    specs: { Type: 'Puree treat', Protein: 'Chicken', Count: '50 tubes', Calories: 'Low' }
  },
  {
    id: 60,
    name: 'Tetra Water Cleaner Gravel Siphon for Aquariums',
    category: 'Pet Supplies',
    rating: 4.4,
    reviews: 23456,
    image: 'https://m.media-amazon.com/images/I/71POJ-eqDWL._AC_SX679_.jpg',
    link: 'https://www.amazon.com/Tetra-Cleaner-Gravel-Aquariums-Freshwater/dp/B091D3DTWS',
    description: 'Easy-to-use aquarium vacuum that removes debris from gravel while changing water, keeps tank clean and healthy',
    longDescription: 'Easy-to-use aquarium vacuum and gravel cleaner that removes debris and waste from gravel beds while performing water changes. Self-starting siphon design makes water changes simple and mess-free.',
    features: ['Gravel cleaning', 'Water changing', 'Self-starting siphon', 'Easy to use'],
    specs: { Type: 'Gravel Vacuum', Size: '16 inch', Use: 'Freshwater tanks', Design: 'Self-start' }
  }
]
