export const products = [
  // Electronics
  {
    id: 1,
    name: "Amazon Echo Studio",
    category: "Electronics",
    price: 199.99,
    rating: 4.7,
    reviews: 28542,
    image: "https://m.media-amazon.com/images/I/71BRtVq+uWL._AC_SL1500_.jpg",
    link: "https://www.amazon.com/dp/B0FBHDQ94L?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=4cd3efdb787ed10d584a3acabde6d449&language=en_US&ref_=as_li_ss_tl",
    description:
      "Premium smart speaker with immersive, room-filling sound, spatial audio processing, and Alexa voice control for the ultimate listening experience",
    longDescription:
      "Amazon Echo Studio delivers studio-quality sound with five strategically positioned speakers for powerful bass, dynamic midrange, and crisp highs. Featuring Dolby Atmos and spatial audio processing technology, it adapts to any room's acoustics for an immersive 3D audio experience. Control your music, smart home, and more with Alexa.",
    features: [
      "Dolby Atmos spatial audio",
      "5 directional speakers",
      "Automatic room adaptation",
      "Alexa built-in",
      "Smart home hub",
      "Hi-res lossless audio",
    ],
    specs: {
      Brand: "Amazon",
      Model: "Echo Studio",
      Connectivity: "Wi-Fi, Bluetooth, Zigbee",
      Color: "Charcoal",
      Weight: "7.7 lbs",
    },
  },
  {
    id: 2,
    name: "Amazon Fire TV Stick 4K Select (newest model)",
    category: "Electronics",
    price: 54.99,
    rating: 4.6,
    reviews: 8912,
    image: "https://m.media-amazon.com/images/I/71B2hSrvyZL._AC_SY450_.jpg",
    link: "https://www.amazon.com/amazon-fire-tv-stick-4K-select/dp/B0C6W3D4RM?&linkCode=ll1&tag=marketplaza0b-20&linkId=81d83797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description:
      "Stream in stunning 4K Ultra HD with support for Dolby Vision, HDR10+, and immersive Dolby Atmos audio",
    longDescription:
      "Stream in stunning 4K Ultra HD with support for Dolby Vision, HDR10+, and immersive Dolby Atmos audio. Access thousands of channels, apps, and Alexa skills with this powerful streaming device.",
    features: ["4K Ultra HD streaming", "Dolby Vision & HDR10+", "Dolby Atmos audio", "Alexa voice remote"],
    specs: { Resolution: "4K Ultra HD", Streaming: "Wi-Fi 6", Voice: "Alexa", Storage: "8GB" },
  },
  {
    id: 3,
    name: "Apple AirPods Pro 2 Wireless Earbuds",
    category: "Electronics",
    price: 249.99,
    originalPrice: 299.99,
    rating: 4.8,
    reviews: 32456,
    image: "https://m.media-amazon.com/images/I/611pEx7220L._AC_SX522_.jpg",
    link: "https://www.amazon.com/Apple-Cancellation-Transparency-Personalized-High-Fidelity/dp/B0D1XD1ZV3?&linkCode=ll1&tag=marketplaza0b-20&linkId=04a9286d70d9246ac7e6693261e914f9&language=en_US&ref_=as_li_ss_tl",
    description:
      "Premium wireless earbuds with adaptive active noise cancellation, transparency mode, and personalized spatial audio",
    longDescription:
      "Premium wireless earbuds with up to 2x more active noise cancellation than the previous generation. Features Adaptive Audio that automatically adjusts noise control to your environment and personalized spatial audio for an immersive listening experience.",
    features: [
      "Active Noise Cancellation",
      "Adaptive Audio",
      "Transparency mode",
      "Personalized Spatial Audio",
      "Up to 6 hours listening time",
    ],
    specs: {
      Brand: "Apple",
      Model: "AirPods Pro 2",
      Battery: "Up to 30 hours with case",
      Connectivity: "Bluetooth 5.3",
    },
  },
  {
    id: 4,
    name: "Anker Power Bank (PowerCore 10K)",
    category: "Electronics",
    price: 29.99,
    rating: 4.7,
    reviews: 18765,
    image: "https://m.media-amazon.com/images/I/71JJLJnwREL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Anker-Travel-Ready-Technology-High-Speed-Output%EF%BC%88Black%EF%BC%89%EF%BC%8C1pack/dp/B0D5CLSMFB?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=796b92b77e0ab3bbe896480e8ddc37db&language=en_US&ref_=as_li_ss_tl",
    description: "Ultra-compact 10,000mAh portable charger with PowerIQ technology for fast charging on the go",
    longDescription:
      "Ultra-compact 10,000mAh portable charger with PowerIQ technology that intelligently identifies your device for the fastest possible charge. Slim design fits easily in pockets and bags while providing multiple full phone charges.",
    features: ["10,000mAh capacity", "PowerIQ fast charging", "Ultra-compact design", "Universal compatibility"],
    specs: { Capacity: "10,000mAh", Output: "12W", Weight: "6.56 oz", Ports: "USB-A" },
  },
  {
    id: 5,
    name: "SAMSUNG Galaxy S25 Ultra",
    category: "Electronics",
    price: 1299.99,
    rating: 4.9,
    reviews: 4567,
    image: "https://m.media-amazon.com/images/I/61n0lmxP5-L._AC_SX679_.jpg",
    link: "https://www.amazon.com/Smartphone-Unlocked-Processor-Manufacturer-Warranty/dp/B0DP3G4GVQ?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=6e5e3a13f8c8b3a148309c2b19704317&language=en_US&ref_=as_li_ss_tl",
    description:
      "Flagship unlocked smartphone with advanced processor, stunning display, and professional-grade camera system",
    longDescription:
      "Flagship unlocked smartphone featuring the latest Snapdragon processor, stunning 6.8-inch Dynamic AMOLED display with 120Hz refresh rate, and a professional quad-camera system with advanced AI features for stunning photos and videos.",
    features: [
      '6.8" Dynamic AMOLED display',
      "Snapdragon processor",
      "Quad camera system",
      "5000mAh battery",
      "S Pen included",
    ],
    specs: { Display: '6.8" AMOLED', Storage: "256GB", RAM: "12GB", Camera: "200MP main" },
  },

  // Home & Kitchen
  {
    id: 6,
    name: "Instant Pot Duo 7-in-1 Electric Pressure Cooker",
    category: "Home & Kitchen",
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.7,
    reviews: 142567,
    image: "https://m.media-amazon.com/images/I/71Z401LjFFL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Instant-Pot-Multi-Use-Programmable-Pressure/dp/B00FLYWNYQ?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=f85d3eb1fc0d00d37346ca429fd65766&language=en_US&ref_=as_li_ss_tl",
    description:
      "Multi-functional programmable cooker combining pressure cooker, slow cooker, rice cooker, steamer, and more",
    longDescription:
      "7-in-1 programmable cooker that replaces multiple kitchen appliances. Functions as pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and warmer. Makes cooking fast, easy, and convenient.",
    features: ["7-in-1 functionality", "14 smart programs", "6-quart capacity", "Stainless steel pot"],
    specs: { Capacity: "6 Quart", Functions: "7-in-1", Wattage: "1000W", Material: "Stainless Steel" },
  },
  {
    id: 7,
    name: "Ninja Air Fryer",
    category: "Home & Kitchen",
    price: 89.99,
    rating: 4.8,
    reviews: 67234,
    image: "https://m.media-amazon.com/images/I/71+8uTMDRFL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Ninja-AF101-Fryer-Black-gray/dp/B07FDJMC9Q?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=c3960821a8395b741a4371cff92b5a80&language=en_US&ref_=as_li_ss_tl",
    description: "Compact air fryer with wide temperature range for guilt-free crispy favorites using little to no oil",
    longDescription:
      "Compact yet powerful air fryer that uses rapid air circulation technology to cook food with up to 75% less fat than traditional frying methods. Wide temperature range allows for versatile cooking from dehydrating to air frying.",
    features: ["4-quart capacity", "400°F max temperature", "Dishwasher safe basket", "Compact design"],
    specs: { Capacity: "4 Quart", Temperature: "105-400°F", Wattage: "1550W", Coating: "Nonstick" },
  },
  {
    id: 8,
    name: "ZINUS 12 Inch King Green Tea Memory Foam Mattress",
    category: "Home & Kitchen",
    price: 319.99,
    originalPrice: 449.99,
    rating: 4.6,
    reviews: 28945,
    image: "https://m.media-amazon.com/images/I/81XzXrlHljL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Zinus-Mattress-Fiberglass-Pressure-Certified/dp/B0CKZ1CK1H?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=5b60004272ac3709382ebca9b58f249e&language=en_US&ref_=as_li_ss_tl",
    description:
      "Premium memory foam mattress infused with green tea extract for natural odor control and pressure relief",
    longDescription:
      "Premium 12-inch memory foam mattress featuring green tea extract infusion for natural freshness and odor control. Multiple layers of foam provide superior pressure relief and support for a restful night's sleep.",
    features: ["Green tea infusion", "12-inch thickness", "Pressure relieving foam", "CertiPUR-US certified"],
    specs: { Size: "King", Thickness: "12 inches", Material: "Memory Foam", Certification: "CertiPUR-US" },
  },
  {
    id: 9,
    name: "Rubbermaid Brilliance Storage 14-Piece Plastic Containers",
    category: "Home & Kitchen",
    price: 39.99,
    rating: 4.8,
    reviews: 45678,
    image: "https://m.media-amazon.com/images/I/81E+ZZQJ+OL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Rubbermaid-Brilliance-Storage-Container-BPA-free/dp/B079M8FPTW?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=0ce57ee92972e282a390c411718fd0e7&language=en_US&ref_=as_li_ss_tl",
    description:
      "BPA-free food storage containers with crystal-clear lids and leak-proof seals for organized freshness",
    longDescription:
      "Premium food storage containers featuring crystal-clear Tritan material for easy visibility and 100% leak-proof seals. Microwave, dishwasher, and freezer safe for ultimate convenience in meal prep and storage.",
    features: ["100% leak-proof", "Crystal-clear Tritan", "Microwave & dishwasher safe", "Modular stacking"],
    specs: { Material: "BPA-free Tritan", Set: "14-piece", "Seal Type": "Leak-proof latch", Uses: "Multi-purpose" },
  },
  {
    id: 10,
    name: "Shark Navigator Professional Upright Vacuum",
    category: "Home & Kitchen",
    price: 179.99,
    rating: 4.7,
    reviews: 34567,
    image: "https://m.media-amazon.com/images/I/71xtMDDPzRL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Shark-Navigator-Professional-Anti-Allergy-NV360/dp/B00JH98GR4?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=4b52d28573fc51f76f8d785e8fba34cc&language=en_US&ref_=as_li_ss_tl",
    description: "Powerful upright vacuum with lift-away technology and HEPA filter for versatile whole-home cleaning",
    longDescription:
      "Professional upright vacuum with powerful suction and complete seal technology to trap dust and allergens. Features swivel steering for easy navigation around furniture and a lift-away canister for portable cleaning.",
    features: ["Anti-Allergy Complete Seal", "HEPA filter", "Swivel steering", "Lift-Away technology"],
    specs: { Type: "Upright", Filtration: "HEPA", Capacity: "2.2 Quarts", Cord: "25 ft" },
  },

  // Beauty & Personal Care
  {
    id: 11,
    name: "CeraVe Skin Renewing Night Cream",
    category: "Beauty & Personal Care",
    price: 18.99,
    rating: 4.6,
    reviews: 23456,
    image: "https://m.media-amazon.com/images/I/71uiH7D0URL._SX679_.jpg",
    link: "https://www.amazon.com/CeraVe-Skin-Renewing-Night-Cream/dp/B00SNPCSUY?&linkCode=ll1&tag=marketplaza0b-20&linkId=8f39fc27811dbb9f08f81d72b2117f16&language=en_US&ref_=as_li_ss_tl",
    description: "Nourishing night cream with ceramides and hyaluronic acid for hydrated, smoother-looking skin",
    longDescription:
      "Nourishing night cream formulated with three essential ceramides, hyaluronic acid, and peptide complex to help restore and maintain the skin's natural protective barrier while you sleep. Non-comedogenic and fragrance-free.",
    features: ["3 essential ceramides", "Hyaluronic acid", "Peptide complex", "Fragrance-free"],
    specs: { Size: "1.7 oz", Type: "Night Cream", Skin: "All types", Formula: "Non-comedogenic" },
  },
  {
    id: 12,
    name: "The Ordinary Hyaluronic Acid 2% + B5",
    category: "Beauty & Personal Care",
    price: 8.99,
    rating: 4.5,
    reviews: 67890,
    image: "https://m.media-amazon.com/images/I/51tYxN1QYCL._SX679_.jpg",
    link: "https://www.amazon.com/Ordinary-Hyaluronic-Acid-2-30ml/dp/B01MYEZPC8?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=8a4f73bf92977ff2f8b39df4e9202f50&language=en_US&ref_=as_li_ss_tl",
    description: "Hydration serum with multiple molecular weights of hyaluronic acid for multi-depth hydration",
    longDescription:
      "Lightweight water-based serum combining low, medium, and high molecular weight hyaluronic acid molecules along with a next-generation HA crosspolymer for multi-depth hydration. Enhanced with vitamin B5 for improved surface hydration.",
    features: ["Multi-weight hyaluronic acid", "Vitamin B5", "Lightweight texture", "Deep hydration"],
    specs: { Size: "30ml", Type: "Serum", Concentration: "2%", Vegan: "Yes" },
  },
  {
    id: 13,
    name: "Laneige Lip Sleeping Mask",
    category: "Beauty & Personal Care",
    price: 24.0,
    rating: 4.7,
    reviews: 34567,
    image: "https://m.media-amazon.com/images/I/61BQnr32+aL._SX679_.jpg",
    link: "https://www.amazon.com/Laneige-Sleeping-Berry/dp/B07XXPHQZK?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=eb7fe6aced122cedc39f419093298f7b&language=en_US&ref_=as_li_ss_tl",
    description: "Overnight lip treatment that softens and moisturizes for smooth, supple lips by morning",
    longDescription:
      "Overnight lip treatment featuring Berry Mix Complex™ rich in antioxidants and Vitamin C. The balmy texture forms a protective film that locks in moisture and active ingredients for visibly smoother, more supple lips by morning.",
    features: ["Berry Mix Complex", "Overnight moisture", "Antioxidant-rich", "Smooth texture"],
    specs: { Size: "20g", Type: "Lip Mask", Flavor: "Berry", Use: "Overnight" },
  },
  {
    id: 14,
    name: "Neutrogena Makeup Remover Wipes (25 Count, 3 Pack)",
    category: "Beauty & Personal Care",
    price: 8.47,
    rating: 4.7,
    reviews: 89012,
    image: "https://m.media-amazon.com/images/I/71HJ5kQ4gQL._SX679_.jpg",
    link: "https://www.amazon.com/Neutrogena-Makeup-Remover-Wipes-Count/dp/B004Y9H2LQ?tag=marketplaza0b-20",
    description: "Ultra-soft makeup remover cleansing towelettes that dissolve all traces of makeup",
    longDescription:
      "Ultra-soft makeup remover cleansing towelettes that dissolve all traces of makeup, including waterproof mascara. Alcohol-free and dermatologist-tested formula is gentle on the skin.",
    features: ["Removes all makeup", "Waterproof mascara", "Alcohol-free", "Gentle formula"],
    specs: { Count: "75 wipes", Type: "Cleansing Towelettes", Brand: "Neutrogena", Dermatologist: "Tested" },
  },
  {
    id: 15,
    name: "e.l.f. Power Grip Primer",
    category: "Beauty & Personal Care",
    price: 10.0,
    rating: 4.5,
    reviews: 45678,
    image: "https://m.media-amazon.com/images/I/61Ni3QOXKUL._SL1500_.jpg",
    link: "https://www.amazon.com/l-f-Power-Grip-Primer-Enhancing/dp/B084Q5CQS9?&linkCode=ll1&tag=marketplaza0b-20&linkId=818d3797e1b4495aaa0287566855caf8&language=en_US&ref_=as_li_ss_tl",
    description: "Gel-based face primer with a tacky texture that grips makeup for long-lasting wear",
    longDescription:
      "Gel-based face primer with a tacky texture that grips makeup for long-lasting wear, creating a smooth canvas for foundation. Infused with hydrating ingredients like hyaluronic acid and vitamin E.",
    features: ["Gripping formula", "Long-lasting wear", "Smooths skin", "Hydrating"],
    specs: { Size: "1.01 oz", Type: "Face Primer", Finish: "Matte", Vegan: "Yes" },
  },

  // Clothing, Shoes & Jewelry
  {
    id: 16,
    name: "Hanes Men's Pullover EcoSmart Hooded Sweatshirt",
    category: "Clothing, Shoes & Jewelry",
    price: 13.0,
    rating: 4.5,
    reviews: 123456,
    image: "https://m.media-amazon.com/images/I/81dQAf7PSOL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Hanes-EcoSmart-Fleece-Sweatshirt-Stonewashed/dp/B0721C21RJ?th=1&psc=1&linkCode=ll1&tag=marketplaza0b-20&linkId=da35504c0b579d6450b5589c8da2e811&language=en_US&ref_=as_li_ss_tl",
    description: "Comfortable pullover hoodie made with eco-smart fleece containing recycled polyester fibers",
    longDescription:
      "Classic crewneck sweatshirt made with EcoSmart fleece containing up to 5% recycled polyester from plastic bottles. Soft, medium-weight fabric provides warmth without bulk for comfortable everyday wear.",
    features: ["EcoSmart fleece", "Ribbed cuffs", "Pill-resistant", "Tag-free"],
    specs: { Material: "50/50 Cotton/Poly", Fit: "Regular", Weight: "Medium", Eco: "5% Recycled" },
  },
  {
    id: 17,
    name: "Hanes Men's Full-Zip Eco-smart Hoodie",
    category: "Clothing, Shoes & Jewelry",
    price: 14.0,
    rating: 4.5,
    reviews: 98765,
    image: "https://m.media-amazon.com/images/I/81GQc1YlRmL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Hanes-Full-zip-Eco-smart-athletic-sweatshirts/dp/B00JUM4CT4?th=1&psc=1&linkCode=ll1&tag=marketplaza0b-20&linkId=33e5c4a83b34d758eb9b87796973935a&language=en_US&ref_=as_li_ss_tl",
    description: "Full-zip athletic hoodie with front pockets and eco-friendly fabric from recycled materials",
    longDescription:
      "Full-zip hoodie featuring EcoSmart fleece made with up to 5% recycled polyester. Full-length zipper allows for easy on/off and ventilation control. Kangaroo pocket provides convenient storage for essentials.",
    features: ["Full-zip design", "Kangaroo pocket", "EcoSmart fleece", "Adjustable hood"],
    specs: { Material: "50/50 blend", Closure: "Full-zip", Pockets: "Kangaroo", Fit: "Regular" },
  },
  {
    id: 18,
    name: "Adidas Men's Lite Racer Adapt 7.0 Sneaker",
    category: "Clothing, Shoes & Jewelry",
    price: 50.0,
    rating: 4.5,
    reviews: 56789,
    image: "https://m.media-amazon.com/images/I/71PZz8PVSQL._AC_SY695_.jpg",
    link: "https://www.amazon.com/adidas-Racer-Adapt-Sneaker-Black/dp/B0CKMC1BGB?th=1&psc=1&linkCode=ll1&tag=marketplaza0b-20&linkId=2e9a3afb28afb38952d1e217a41242ac&language=en_US&ref_=as_li_ss_tl",
    description: "Lightweight running-inspired sneakers with Cloudfoam cushioning for all-day comfort",
    longDescription:
      "Running-inspired sneakers featuring a breathable mesh upper and Cloudfoam midsole for step-in comfort and superior cushioning. Slip-on design with elastic laces makes them easy to wear while maintaining a secure fit.",
    features: ["Cloudfoam cushioning", "Mesh upper", "Slip-on design", "Flexible sole"],
    specs: { Brand: "adidas", Type: "Running shoe", Upper: "Mesh", Sole: "Rubber" },
  },
  {
    id: 19,
    name: "Levi's Men's 511 Slim Fit Jeans",
    category: "Clothing, Shoes & Jewelry",
    price: 39.5,
    originalPrice: 69.5,
    rating: 4.5,
    reviews: 234567,
    image: "https://m.media-amazon.com/images/I/81xW+cGe0LL._AC_SY741_.jpg",
    link: "https://www.amazon.com/Levis-Mens-Jeans-Stretch-Panda/dp/B072NGDWDY?th=1&psc=1&linkCode=ll1&tag=marketplaza0b-20&linkId=0068877542a76eda70a8f4f7c59ecdc4&language=en_US&ref_=as_li_ss_tl",
    description: "Classic slim fit jeans with stretch denim for comfortable movement and timeless style",
    longDescription:
      "Iconic 511 Slim Fit jeans featuring a slim fit through the hip and thigh with a slightly tapered leg. Made with premium stretch denim for comfortable movement while maintaining the classic Levi's quality and style.",
    features: ["Slim fit", "Stretch denim", "Five-pocket styling", "Zip fly"],
    specs: { Fit: "Slim", Rise: "Medium", Material: "Stretch Denim", Closure: "Zipper" },
  },
  {
    id: 20,
    name: "Casio Men's MDV106-1AV Analog Watch",
    category: "Clothing, Shoes & Jewelry",
    price: 52.95,
    rating: 4.7,
    reviews: 67890,
    image: "https://m.media-amazon.com/images/I/81R5vYdNEsL._AC_SY741_.jpg",
    link: "https://www.amazon.com/Casio-MDV106-1AV-Analog-Watch-Black/dp/B009KYJAJY?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=f91c27d47973faf389807bb435e88deb&language=en_US&ref_=as_li_ss_tl",
    description: "Durable dive watch with 200M water resistance, date display, and reliable quartz movement",
    longDescription:
      "Professional dive-style analog watch featuring 200-meter water resistance, unidirectional rotating bezel, and luminous hands and markers for underwater visibility. Durable resin band and reliable Japanese quartz movement.",
    features: ["200m water resistant", "Rotating bezel", "Luminous markers", "Quartz movement"],
    specs: { Movement: "Quartz", "Water Resistance": "200m", Display: "Analog", Band: "Resin" },
  },
  {
    id: 21,
    name: "Fossil Women's Fiona Small Crossbody Handbag",
    category: "Clothing, Shoes & Jewelry",
    price: 78.0,
    rating: 4.6,
    reviews: 12345,
    image: "https://m.media-amazon.com/images/I/81ek+CxDG7L._AC_SX679_.jpg",
    link: "https://www.amazon.com/Fossil-Fiona-EW-Crossbody-Brown/dp/B07DLMZ4C7?th=1&psc=1&linkCode=ll1&tag=marketplaza0b-20&linkId=7076c7115004be96ad3365fb7bbcfa71&language=en_US&ref_=as_li_ss_tl",
    description: "Compact leather crossbody bag with adjustable strap and multiple compartments for essentials",
    longDescription:
      "Sophisticated crossbody handbag crafted from quality leather with multiple interior pockets and card slots for organized storage. Adjustable strap allows for comfortable wear as crossbody or shoulder bag.",
    features: ["Genuine leather", "Adjustable strap", "Multiple pockets", "Zip closure"],
    specs: { Material: "Leather", Size: "Small", Strap: "Adjustable", Closure: "Zipper" },
  },

  // Toys & Games
  {
    id: 22,
    name: "LEGO Classic Medium Creative Brick Box",
    category: "Toys & Games",
    price: 29.99,
    rating: 4.9,
    reviews: 89012,
    image: "https://m.media-amazon.com/images/I/715sgjh0rmL._AC_SX679_.jpg",
    link: "https://www.amazon.com/LEGO-Classic-Medium-Creative-Brick/dp/B00NHQFA1I?&linkCode=ll1&tag=marketplaza0b-20&linkId=d5e1b2125b26f7556c122d792ac11f75&language=en_US&ref_=as_li_ss_tl",
    description: "484-piece building brick set with classic LEGO pieces in vibrant colors for creative construction",
    longDescription:
      "Creative building set featuring 484 pieces in 35 different colors for endless building possibilities. Includes windows, eyes, and wheels plus a building ideas booklet to inspire creativity and imagination.",
    features: ["484 pieces", "35 colors", "Building ideas included", "Classic LEGO bricks"],
    specs: { Pieces: 484, Ages: "4+", Theme: "Classic", Type: "Building Set" },
  },
  {
    id: 23,
    name: "UNO Spin Card Game",
    category: "Toys & Games",
    price: 11.99,
    rating: 4.8,
    reviews: 45678,
    image: "https://m.media-amazon.com/images/I/810t+LPr8PL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Mattel-Games-Adults-Parties-Special/dp/B0D6X9T62X?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=747ea56a489e1140df8f0b0776733719&language=en_US&ref_=as_li_ss_tl",
    description: "Classic card game with electronic spinner adding exciting twists and unpredictable gameplay",
    longDescription:
      "Classic UNO game with a team play twist that adds a new level of strategy and excitement. Players work together with their teammate to be the first team to get rid of all their cards. Perfect for 4+ players.",
    features: ["Team gameplay", "4+ players", "Quick setup", "Travel-friendly"],
    specs: { Players: "4+", Ages: "7+", "Play Time": "30 min", Cards: "112" },
  },
  {
    id: 24,
    name: "Barbie Dreamhouse, 3-Story Dollhouse Playset",
    category: "Toys & Games",
    price: 179.99,
    originalPrice: 239.99,
    rating: 4.8,
    reviews: 23456,
    image: "https://m.media-amazon.com/images/I/81KQIXUfxnL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Barbie-Dreamhouse-3-Story-Playset-Elevator/dp/B0BLJTJ38M?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=27806ffda86bdbf46c43db8583b2bd73&language=en_US&ref_=as_li_ss_tl",
    description: "Three-story dollhouse with working elevator, pool, and 70+ accessories for imaginative play",
    longDescription:
      "Iconic 3-story Dreamhouse featuring 8 rooms, a working elevator, pool with slide, and 75+ accessories. Interactive features include lights, sounds, and transformation play pieces for endless storytelling possibilities.",
    features: ["3 stories, 8 rooms", "Working elevator", "Pool with slide", "75+ accessories"],
    specs: { Height: "3.75 feet", Rooms: "8", Features: "Lights & sounds", Ages: "3+" },
  },
  {
    id: 25,
    name: "Nintendo Switch Super Mario Bros. Wonder Bundle",
    category: "Toys & Games",
    price: 349.99,
    rating: 4.8,
    reviews: 12345,
    image: "https://m.media-amazon.com/images/I/61oiNaMKM7L._AC_SX679_.jpg",
    link: "https://www.amazon.com/Nintendo-Switch-Mario-World-Bundle-2/dp/B0FC5FJZ9Z?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=4f7e258ea3d84aa3d5dd17abbb142b27&language=en_US&ref_=as_li_ss_tl",
    description: "Gaming console bundle with Super Mario Bros. Wonder game for multiplayer adventure fun",
    longDescription:
      "Next-generation Switch console with enhanced graphics and performance. Bundle includes Super Mario Bros. Wonder game. Play on TV at home or take it on the go for portable gaming experiences.",
    features: ["Portable & TV mode", "Enhanced graphics", "Super Mario Bros. Wonder included", "Multiplayer ready"],
    specs: { Screen: '7" OLED', Storage: "64GB", Battery: "9 hours", Controllers: "2 Joy-Cons" },
  },
  {
    id: 26,
    name: "Play-Doh Modeling Compound 36-Pack",
    category: "Toys & Games",
    price: 17.99,
    rating: 4.8,
    reviews: 67890,
    image: "https://m.media-amazon.com/images/I/91fNVW3+iML._AC_SX679_.jpg",
    link: "https://www.amazon.com/Play-Doh-Modeling-Compound-Non-Toxic-Exclusive/dp/B00JM5GW10?&linkCode=ll1&tag=marketplaza0b-20&linkId=9ce2d903a87e1e715c1a26ecc54a70c9&language=en_US&ref_=as_li_ss_tl",
    description: "36 vibrant colors of non-toxic modeling compound for creative sculpting and imaginative play",
    longDescription:
      "Classic modeling compound in 36 different vibrant colors. Non-toxic formula is safe for creative play. Each can contains 2 ounces of soft, pliable compound perfect for molding, sculpting, and imaginative creations.",
    features: ["36 vibrant colors", "Non-toxic formula", "2 oz per can", "Soft & pliable"],
    specs: { Colors: "36", Amount: "72 oz total", Ages: "2+", Safe: "Non-toxic" },
  },

  // Health & Household / Baby
  {
    id: 27,
    name: "Pampers Aqua Pure Sensitive Water Baby Wipes",
    category: "Health & Household",
    price: 29.94,
    rating: 4.8,
    reviews: 34567,
    image: "https://m.media-amazon.com/images/I/71aoWs2pNVL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Pampers-Wipes-Sensitive-Perfume-Multi/dp/B0BJ13K7FR?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=04f776e7b484d65939421619bbe1d33a&language=en_US&ref_=as_li_ss_tl",
    description: "Gentle water-based baby wipes made with 99% pure water for sensitive skin care",
    longDescription:
      "Hypoallergenic and perfume-free baby wipes with a clinically proven mild formula. Thick and gentle, these wipes are perfect for sensitive skin and provide a thorough clean with every wipe.",
    features: ["Hypoallergenic", "Perfume-free", "Clinically proven mild", "Thick & gentle"],
    specs: { Count: "12 packs", "Per Pack": "56 wipes", Total: "672 wipes", pH: "Balanced" },
  },
  {
    id: 28,
    name: "Charmin Ultra Soft Toilet Paper, 18 Family Mega Rolls",
    category: "Health & Household",
    price: 37.49,
    rating: 4.8,
    reviews: 89012,
    image: "https://m.media-amazon.com/images/I/817K05FNh9L._AC_SX679_.jpg",
    link: "https://www.amazon.com/Charmin-Toilet-Family-Cushiony-Sheets/dp/B0798DVT68?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=18588762a05ef1a3db7cdd56e8d20407&language=en_US&ref_=as_li_ss_tl",
    description: "Soft, strong bathroom tissue with cushiony comfort and long-lasting family mega rolls",
    longDescription:
      "Luxuriously soft and absorbent 2-ply toilet paper with Charmin's signature cushiony texture. Septic-safe and clog-safe when used as directed. Each Family Mega Roll has 264 sheets.",
    features: ["2-ply softness", "Cushiony texture", "Septic-safe", "Clog-safe"],
    specs: { Rolls: "24 Family Mega", "Sheets per Roll": 264, Ply: "2-ply", Safe: "Septic-safe" },
  },
  {
    id: 29,
    name: "Nature's Way Sambucus Elderberry Gummies",
    category: "Health & Household",
    price: 15.74,
    rating: 4.6,
    reviews: 45678,
    image: "https://m.media-amazon.com/images/I/81n9KJPuaXL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Natures-Way-Elderberry-Vegetarian-Packaging/dp/B00MJ7VL1O?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=3b36901da45e9f7c94ec754f68f38e19&language=en_US&ref_=as_li_ss_tl",
    description: "Immune support elderberry gummies with vitamin C and zinc for daily wellness",
    longDescription:
      "Delicious vegetarian gummies made with premium black elderberry extract plus vitamin C and zinc for immune support. Great tasting and pectin-based formula suitable for the whole family.",
    features: ["Black elderberry", "Vitamin C & Zinc", "Vegetarian", "Great taste"],
    specs: { Count: "60 gummies", Servings: "30", Type: "Gummy", Vegetarian: "Yes" },
  },
  {
    id: 30,
    name: "Huggies Natural Care Sensitive Baby Wipes",
    category: "Baby",
    price: 19.97,
    rating: 4.8,
    reviews: 123456,
    image: "https://m.media-amazon.com/images/I/81N7aCUoi1L._AC_SX679_.jpg",
    link: "https://www.amazon.com/HUGGIES-Natural-Unscented-Sensitive-Water-Based/dp/B07SCL613T?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=9281da5ee7355645759c902aea4040b7&language=en_US&ref_=as_li_ss_tl",
    description: "Gentle, fragrance-free baby wipes with aloe and vitamin E for sensitive skin",
    longDescription:
      "Water-based baby wipes made with 99% purified water and gentle plant-derived ingredients. Unscented and hypoallergenic formula is clinically proven gentle for sensitive skin. Thick and absorbent.",
    features: ["99% water", "Plant-derived", "Unscented", "Hypoallergenic"],
    specs: { Packs: "12", "Per Pack": "56 wipes", Total: "672 wipes", Base: "Water" },
  },
  {
    id: 31,
    name: "Philips Avent Natural Baby Bottle Set",
    category: "Baby",
    price: 32.99,
    rating: 4.7,
    reviews: 23456,
    image: "https://m.media-amazon.com/images/I/61h0xpsDIuL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Philips-Natural-Response-SCY910-04/dp/B098YHHV3Q?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=3057aa200e5a633f518b563e9302239b&language=en_US&ref_=as_li_ss_tl",
    description: "Natural feeding bottle set with wide breast-shaped nipple for easy latch and natural feeding",
    longDescription:
      "Premium glass baby bottles featuring Natural Response nipples with an innovative opening that releases milk only when baby actively drinks. Glass material is easy to clean and naturally BPA-free.",
    features: ["Natural Response nipple", "Glass material", "Anti-colic", "BPA-free"],
    specs: { Material: "Glass", Size: "8 oz", Count: "4 bottles", Nipple: "Natural Response" },
  },

  // Sports & Outdoors
  {
    id: 32,
    name: "Fitbit Charge 6 Fitness Tracker",
    category: "Sports & Outdoors",
    price: 159.95,
    rating: 4.4,
    reviews: 12345,
    image: "https://m.media-amazon.com/images/I/61xh-IyqBmL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Fitbit-Exercise-Equipment-6-Months-Membership/dp/B0CC62ZG1M?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=c4108f31d1afeb88655325cef8256f96&language=en_US&ref_=as_li_ss_tl",
    description: "Advanced fitness tracker with built-in GPS, heart rate monitoring, and 6 months Premium membership",
    longDescription:
      "Advanced fitness tracker with built-in GPS, 24/7 heart rate monitoring, and Google apps integration. Track workouts, sleep, stress, and more. Includes 6-month Fitbit Premium membership.",
    features: ["Built-in GPS", "Heart rate monitoring", "Google apps", "40+ exercise modes"],
    specs: { Display: "AMOLED", Battery: "7 days", "Water Resistance": "50m", Connectivity: "Bluetooth" },
  },
  {
    id: 33,
    name: "Coleman Sundome Camping Tent",
    category: "Sports & Outdoors",
    price: 59.99,
    rating: 4.6,
    reviews: 45678,
    image: "https://m.media-amazon.com/images/I/81fDlI05yiL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Coleman-Weatherproof-Festivals-Backyard-Sleepovers/dp/B0D7QLQNS5?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=4f3e5b076c9ae52488980ac295380bba&language=en_US&ref_=as_li_ss_tl",
    description: "Easy setup camping tent with WeatherTec system for weatherproof outdoor adventures",
    longDescription:
      "Weatherproof dome tent featuring WeatherTec system with patented welded floors and inverted seams to keep water out. Easy setup with snag-free Insta-Clip pole attachments. Fits 2-4 people.",
    features: ["WeatherTec system", "Easy setup", "Vented windows", "E-port for power"],
    specs: { Capacity: "4 person", Size: "8x7 ft", Height: "4.5 ft", Setup: "Quick" },
  },
  {
    id: 34,
    name: "Under Armour Men's Charged Assert 10 Running Shoe",
    category: "Sports & Outdoors",
    price: 70.0,
    rating: 4.5,
    reviews: 23456,
    image: "https://m.media-amazon.com/images/I/61U+8AUrceL._AC_SY695_.jpg",
    link: "https://www.amazon.com/Under-Armour-Charged-Assert-Running/dp/B09XBWQ9Y9?th=1&psc=1&linkCode=ll1&tag=marketplaza0b-20&linkId=1f57540bc03f435a78524dffe4c96062&language=en_US&ref_=as_li_ss_tl",
    description: "Lightweight running shoes with responsive cushioning and durable outsole for comfort and traction",
    longDescription:
      "Versatile running shoes featuring Charged Cushioning midsole for responsive comfort and support. Lightweight mesh upper provides breathability, while durable leather overlays add stability and structure.",
    features: ["Charged Cushioning", "Mesh upper", "Durable overlays", "Flexible sole"],
    specs: { Type: "Running", Cushioning: "Charged", Upper: "Mesh & Leather", Sole: "Rubber" },
  },
  {
    id: 35,
    name: "Garmin Forerunner 255 GPS Running Smartwatch",
    category: "Sports & Outdoors",
    price: 349.99,
    rating: 4.7,
    reviews: 12345,
    image: "https://m.media-amazon.com/images/I/61Vwqx5FLFL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Garmin-Forerunner-Running-Suggested-Workouts/dp/B092RCLKHN?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=61eb226427ea55cd57e8d76154e0fda8&language=en_US&ref_=as_li_ss_tl",
    description: "Advanced GPS running watch with training metrics, recovery insights, and multi-sport modes",
    longDescription:
      "Easy-to-use GPS running watch with suggested workouts based on your training history and fitness level. Features PacePro pacing guidance, running dynamics, and all-day health monitoring including heart rate and stress.",
    features: ["Built-in GPS", "Suggested workouts", "PacePro guidance", "Health monitoring"],
    specs: { Display: "Sunlight-readable", Battery: "2 weeks", GPS: "Built-in", "Water Rating": "5 ATM" },
  },
  {
    id: 36,
    name: "YETI Rambler 20 oz Tumbler",
    category: "Sports & Outdoors",
    price: 35.0,
    rating: 4.8,
    reviews: 67890,
    image: "https://m.media-amazon.com/images/I/41Y2b7vtBqL._AC_SX679_.jpg",
    link: "https://www.amazon.com/YETI-Rambler-Stainless-Insulated-MagSlider/dp/B08D3VPRQ1?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=7b0241bdfd3ef2254fc590c4208c934e&language=en_US&ref_=as_li_ss_tl",
    description: "Vacuum-insulated stainless steel tumbler with MagSlider lid keeping drinks hot or cold for hours",
    longDescription:
      "Durable travel mug with double-wall vacuum insulation to keep drinks hot or cold for hours. Features MagSlider lid for easy opening and closing, plus a durable handle for convenient carrying. Dishwasher safe.",
    features: ["Double-wall insulated", "MagSlider lid", "Durable handle", "Dishwasher safe"],
    specs: { Capacity: "20 oz", Material: "Stainless Steel", Insulation: "Vacuum", Handle: "Yes" },
  },

  // Books
  {
    id: 37,
    name: "Atomic Habits by James Clear",
    category: "Books",
    price: 13.49,
    rating: 4.8,
    reviews: 234567,
    image: "https://m.media-amazon.com/images/I/81F90H7hnML._SY522_.jpg",
    link: "https://www.amazon.com/Atomic-Habits-James-Clear-audiobook/dp/B07RFSSYBH?&linkCode=ll1&tag=marketplaza0b-20&linkId=8f532b5c9b2ed87a2c4512190d2be3ea&language=en_US&ref_=as_li_ss_tl",
    description: "Practical guide to building good habits and breaking bad ones through tiny behavioral changes",
    longDescription:
      "Practical guide revealing how tiny changes can lead to remarkable results. Learn proven strategies to build good habits, break bad ones, and master the tiny behaviors that lead to remarkable outcomes.",
    features: ["Habit formation", "Behavior change", "Practical strategies", "Real examples"],
    specs: { Author: "James Clear", Pages: "320", Format: "Hardcover", Publisher: "Avery" },
  },
  {
    id: 38,
    name: "The Subtle Art of Not Giving a F*ck by Mark Manson",
    category: "Books",
    price: 13.79,
    rating: 4.6,
    reviews: 123456,
    image: "https://m.media-amazon.com/images/I/71QKQ9mwV7L._SY522_.jpg",
    link: "https://www.amazon.com/Subtle-Art-Not-Giving-Counterintuitive/dp/B01I29Y344?&linkCode=ll1&tag=marketplaza0b-20&linkId=196ef3977d7d0cd9b7bf662b081dd31d&language=en_US&ref_=as_li_ss_tl",
    description: "Counterintuitive approach to living a good life by focusing on what truly matters",
    longDescription:
      "Counterintuitive approach to living a good life that challenges the conventional wisdom of positive thinking. Learn to embrace life's limitations and focus your energy on what truly matters.",
    features: ["Counterintuitive wisdom", "Life philosophy", "Real talk", "Practical advice"],
    specs: { Author: "Mark Manson", Pages: "224", Format: "Paperback", Language: "English" },
  },
  {
    id: 39,
    name: "Harry Potter and the Sorcerer's Stone by J.K. Rowling",
    category: "Books",
    price: 8.99,
    rating: 4.9,
    reviews: 345678,
    image: "https://m.media-amazon.com/images/I/81YOuOGFCJL._SY522_.jpg",
    link: "https://www.amazon.com/Harry-Potter-Sorcerers-Stone-Book/dp/B017V4IMVQ?&linkCode=ll1&tag=marketplaza0b-20&linkId=217def3bac25bf1d92f9a3c017446e3d&language=en_US&ref_=as_li_ss_tl",
    description: "First book in the magical Harry Potter series following a young wizard's adventures at Hogwarts",
    longDescription:
      "Magical beginning of the beloved series following orphan Harry Potter who discovers he's a wizard on his 11th birthday. Join Harry as he attends Hogwarts School of Witchcraft and Wizardry and uncovers his extraordinary destiny.",
    features: ["Fantasy adventure", "Coming of age", "Magic & friendship", "Series starter"],
    specs: { Author: "J.K. Rowling", Pages: "309", Series: "Book 1 of 7", Format: "Hardcover" },
  },
  {
    id: 40,
    name: "The 48 Laws of Power by Robert Greene",
    category: "Books",
    price: 17.99,
    rating: 4.7,
    reviews: 89012,
    image: "https://m.media-amazon.com/images/I/71aG+xDKSYL._SY522_.jpg",
    link: "https://www.amazon.com/48-Laws-of-Power-Robert-Greene-audiobook/dp/B00X0TKUS0?&linkCode=ll1&tag=marketplaza0b-20&linkId=8073d81076f63908d9e556da0cdca27d&language=en_US&ref_=as_li_ss_tl",
    description: "Classic guide to power dynamics with historical examples and strategic insights for success",
    longDescription:
      "Timeless guide distilling 3,000 years of power dynamics into 48 laws. Learn to navigate complex social situations, understand manipulation tactics, and master the subtle art of power in all aspects of life.",
    features: ["Power dynamics", "Strategic thinking", "Historical examples", "Practical laws"],
    specs: { Author: "Robert Greene", Pages: "452", Format: "Paperback", Genre: "Self-help" },
  },

  // Garden & Tools
  {
    id: 41,
    name: "Weber Spirit E-310 Gas Grill",
    category: "Garden & Tools",
    price: 549.0,
    originalPrice: 649.0,
    rating: 4.7,
    reviews: 23456,
    image: "https://m.media-amazon.com/images/I/81Ia9nEKywL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Weber-SPIRIT-3-Burner-Liquid-Propane/dp/B0DPH6NNTB?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=4f955fd70a7ac4a1800ecea826d3d28c&language=en_US&ref_=as_li_ss_tl",
    description: "3-burner liquid propane gas grill with porcelain-enameled lid and cooking grates",
    longDescription:
      "3-burner liquid propane gas grill with porcelain-enameled lid and cooking grates for perfect outdoor BBQ. Features 529 square inches of cooking space, powerful GS4 grilling system, and durable construction.",
    features: [
      "3 stainless steel burners",
      "Porcelain-enameled cast iron grates",
      "Built-in thermometer",
      "Side tables for prep",
    ],
    specs: { Fuel: "Liquid Propane", Burners: "3", "Cooking Area": "529 sq in", Material: "Stainless Steel" },
  },
  {
    id: 42,
    name: "Greenworks 40V Cordless Lawn Mower",
    category: "Garden & Tools",
    price: 299.99,
    rating: 4.5,
    reviews: 12456,
    image: "https://m.media-amazon.com/images/I/71E6jd3Ha0L._AC_SX679_.jpg",
    link: "https://www.amazon.com/dp/B09F9C3KFS?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=d81fe22d5dcb6947d8dfcb8f4dd27257&language=en_US&ref_=as_li_ss_tl",
    description: "Powerful 20-inch cordless mower with brushless motor and durable steel deck for efficient lawn care",
    longDescription:
      "Complete 9-piece gardening tool set including trowel, transplanter, cultivator, weeder, pruner, and more. Ergonomic soft-grip handles reduce hand strain while durable stainless steel heads resist rust and wear.",
    features: ["9 essential tools", "Ergonomic handles", "Stainless steel", "Storage bag included"],
    specs: { Pieces: "9", Material: "Stainless Steel", Handles: "Soft-grip", Includes: "Storage bag" },
  },
  {
    id: 43,
    name: "Best Choice Products 4-Piece Patio Furniture Set",
    category: "Garden & Tools",
    price: 349.99,
    rating: 4.3,
    reviews: 8934,
    image: "https://m.media-amazon.com/images/I/81Hh3i++S-L._AC_SX679_.jpg",
    link: "https://www.amazon.com/dp/B09F3CWRRC?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=4e804ddb5f3c3f2d60ae6642b06cc78d&language=en_US&ref_=as_li_ss_tl",
    description: "All-weather wicker conversation set with cushions perfect for outdoor relaxation and entertaining",
    longDescription:
      "Premium gardening tool collection featuring heavy-duty cast-aluminum heads and comfortable rubberized grips. Set includes all essential tools for digging, weeding, pruning, and transplanting with professional-grade quality.",
    features: ["Cast-aluminum heads", "Rubberized grips", "Professional grade", "Complete set"],
    specs: { Material: "Cast Aluminum", Grip: "Rubberized", Quality: "Professional", Warranty: "1 year" },
  },
  {
    id: 44,
    name: "Victor M250S No Touch, No See Electronic Mouse Trap",
    category: "Garden & Tools",
    price: 24.99,
    rating: 4.2,
    reviews: 15789,
    image: "https://m.media-amazon.com/images/I/61wJQdgnqLL._AC_SX679_.jpg",
    link: "https://www.amazon.com/dp/B07J66MY3Y?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=7ae0d622e5419ede71bd30ae16028dcb&language=en_US&ref_=as_li_ss_tl",
    description: "Hygienic electronic trap delivering humane instant kill with easy no-touch disposal",
    longDescription:
      "Versatile 2-in-1 folding garden kneeler and seat reduces back and knee strain while gardening. Features thick EVA foam pad, sturdy steel frame, two tool pouches, and folds flat for easy storage.",
    features: ["2-in-1 design", "EVA foam pad", "Tool pouches", "Folds flat"],
    specs: { Weight: "Capacity 330 lbs", Frame: "Steel", Pad: "EVA foam", Folding: "Yes" },
  },
  {
    id: 45,
    name: "AmazonBasics Mesh Desk Organizer",
    category: "Garden & Tools",
    price: 15.99,
    rating: 4.7,
    reviews: 34567,
    image: "https://m.media-amazon.com/images/I/81d8Z7DHFfL._AC_SX679_.jpg",
    link: "https://www.amazon.com/dp/B0DBZM45GP?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=a1a7b2d236ef7d7239789ef64f3b0ea7&language=en_US&ref_=as_li_ss_tl",
    description: "Metal mesh desktop organizer with multiple compartments for office supplies and accessories",
    longDescription:
      "Multi-purpose flat shovel with durable steel blade and comfortable D-grip handle. Perfect for edging gardens, moving soil, clearing snow, and scraping ice. Powder-coated finish prevents rust.",
    features: ["Steel blade", "D-grip handle", "Multi-purpose", "Rust-resistant"],
    specs: { Blade: "Steel", Length: "48 inches", Handle: "D-grip", Coating: "Powder-coat" },
  },
  {
    id: 46,
    name: "SereneLife Hanging Egg Chair with Stand",
    category: "Garden & Tools",
    price: 299.99,
    rating: 4.4,
    reviews: 6789,
    image: "https://m.media-amazon.com/images/I/71VEpOvlzWL._AC_SX679_.jpg",
    link: "https://www.amazon.com/JAMFLY-Outdoor-Oversized-Lounger-Backyard/dp/B0D11DZZ5J?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=880f88f9a87321fc9bb67fad53ce96af&language=en_US&ref_=as_li_ss_tl",
    description: "Outdoor lounge chair with cushion and sturdy stand for relaxing in garden or patio",
    longDescription:
      "Oversized wicker egg chair with sturdy steel stand and thick cushions creates a luxurious outdoor relaxation spot. Weather-resistant PE wicker construction perfect for patios, decks, and gardens.",
    features: ["Oversized design", "Steel stand included", "Thick cushions", "Weather-resistant wicker"],
    specs: { Weight: "Capacity 300 lbs", Material: "PE Wicker", Stand: "Steel", Cushion: "Removable" },
  },
  {
    id: 47,
    name: "BLACK+DECKER 20V MAX Cordless Drill",
    category: "Garden & Tools",
    price: 49.99,
    rating: 4.6,
    reviews: 23456,
    image: "https://m.media-amazon.com/images/I/61J3dKtTk9L._AC_SX679_.jpg",
    link: "https://www.amazon.com/Kurapika-Furniture-Outdoor-Conversation-Backyard/dp/B0DP43X8ZJ?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=64c5c03385e2eb340f64dc82ca68cb3f&language=en_US&ref_=as_li_ss_tl",
    description: "Compact cordless drill with lithium battery for drilling and fastening in tight spaces",
    longDescription:
      "Stylish 4-piece outdoor furniture set including 2 single chairs, 1 loveseat, and coffee table. Weather-resistant PE rattan and powder-coated steel frame with thick cushions for comfort.",
    features: ["4-piece set", "Weather-resistant", "Thick cushions", "Steel frame"],
    specs: { Pieces: "4", Material: "PE Rattan", Frame: "Steel", Cushions: "Included" },
  },
  {
    id: 48,
    name: "Scotts Turf Builder Lawn Food",
    category: "Garden & Tools",
    price: 39.98,
    rating: 4.7,
    reviews: 45678,
    image: "https://m.media-amazon.com/images/I/81FJPl7UZCL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Devoko-Furniture-Rattan-Cushion-Outdoor/dp/B0765VTBLV?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=3f02271971bf0279a77adc623b339369&language=en_US&ref_=as_li_ss_tl",
    description: "Premium fertilizer strengthening grass against heat and drought for thick, green lawns",
    longDescription:
      "Comfortable 3-piece rattan patio furniture set with premium cushions. Includes 2 chairs and 1 table. Durable hand-woven PE rattan over sturdy steel frame. Water-resistant cushion covers.",
    features: ["Hand-woven rattan", "Premium cushions", "3-piece set", "Water-resistant covers"],
    specs: { Pieces: "3", Weave: "Hand-woven PE", Frame: "Steel", Covers: "Water-resistant" },
  },
  {
    id: 49,
    name: "Fiskars Steel Bypass Pruning Shears",
    category: "Garden & Tools",
    price: 14.97,
    rating: 4.8,
    reviews: 67890,
    image: "https://m.media-amazon.com/images/I/61mGLCAI9NL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Qsun-Furniture-Conversation-Backyard-Poolside/dp/B09CDNXK56?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=fcca77e174bba46b0dcc762ee6f0a3c7&language=en_US&ref_=as_li_ss_tl",
    description: "Sharp precision-ground steel blade pruning scissors for clean cuts on plants and flowers",
    longDescription:
      "Compact 3-piece bistro set perfect for small spaces including balconies, patios, and poolside areas. Features 2 comfortable chairs and 1 side table. Weather-resistant construction for year-round use.",
    features: ["Compact design", "2 chairs + table", "Weather-resistant", "Small space friendly"],
    specs: { Pieces: "3", Style: "Bistro", "Space Type": "Small", Weather: "Resistant" },
  },
  {
    id: 50,
    name: "Miracle-Gro Indoor Plant Food",
    category: "Garden & Tools",
    price: 7.84,
    rating: 4.6,
    reviews: 12345,
    image: "https://m.media-amazon.com/images/I/71qAb8GBqCL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Mouse-Station-Keys-Required-Stations/dp/B0FDFHPVQ7?&linkCode=ll1&tag=marketplaza0b-20&linkId=45484e735cf780b478006dd801da7b4a&language=en_US&ref_=as_li_ss_tl",
    description: "Liquid fertilizer instantly feeding houseplants with essential nutrients for vibrant growth",
    longDescription:
      "Professional tamper-resistant mouse bait station with secure key-access system for safe pest control around homes, gardens, and outbuildings. Protects children and pets while effectively managing rodent problems.",
    features: ["Key-access security", "Tamper-resistant", "Weather-proof", "Refillable"],
    specs: { Type: "Bait Station", Access: "Key-locked", Use: "Indoor/Outdoor", Material: "Durable plastic" },
  },

  // Pet Supplies
  {
    id: 51,
    name: "Amazon Basics Dog and Puppy Pee Pads with Leak-Proof Design",
    category: "Pet Supplies",
    price: 27.67,
    rating: 4.5,
    reviews: 89012,
    image: "https://m.media-amazon.com/images/I/81+bQvlIo4L._AC_SX679_.jpg",
    link: "https://www.amazon.com/Amazon-Basics-Heavy-Duty-Absorbency-Regular/dp/B00MW8G62E?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=4945eecc05126bf731b54c908b73ba29&language=en_US&ref_=as_li_ss_tl",
    description: "Super-absorbent training pads with 5-layer leak-proof design and quick-dry surface for puppies",
    longDescription:
      "Heavy-duty absorbent training pads with 5-layer leak-proof design including quick-dry surface and built-in attractant. Perfect for puppy training, senior dogs, or pets with special needs.",
    features: ["5-layer protection", "Leak-proof backing", "Quick-dry surface", "Built-in attractant"],
    specs: { Size: "22 x 22 inches", Quantity: "100 count", Absorbency: "Heavy-duty", Type: "Disposable" },
  },
  {
    id: 52,
    name: "Furbo Dog Camera with 360° View",
    category: "Pet Supplies",
    price: 169.99,
    originalPrice: 209.99,
    rating: 4.3,
    reviews: 12345,
    image: "https://m.media-amazon.com/images/I/516pBE3nDtL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Furbo-Camera-with-360%C2%B0-View/dp/B09GDQZLD1?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=5ec03ce0c8bf77be5d72d661b83879cb&language=en_US&ref_=as_li_ss_tl",
    description: "Interactive pet camera with treat tossing, barking alerts, and full room view for monitoring pets",
    longDescription:
      "360-degree rotating pet camera with treat tossing capability, barking alerts, and two-way audio. Features Full HD video, night vision, and smart dog alerts to keep you connected with your furry friend from anywhere.",
    features: ["360° rotation", "Treat tossing", "Two-way audio", "Barking alerts", "Night vision"],
    specs: { Resolution: "1080p", Rotation: "360 degrees", Audio: "2-way", Connectivity: "Wi-Fi" },
  },
  {
    id: 53,
    name: "KONG - Classic Dog Toy",
    category: "Pet Supplies",
    price: 13.99,
    rating: 4.7,
    reviews: 234567,
    image: "https://m.media-amazon.com/images/I/61wcDF7TUHL._AC_SX679_.jpg",
    link: "https://www.amazon.com/KONG-Classic-Durable-Natural-Rubber/dp/B0002AR0II?tag=marketplaza0b-20",
    description: "Durable rubber chew toy that can be stuffed with treats for mental stimulation and play",
    longDescription:
      "Durable rubber chew toy that can be stuffed with treats for mental stimulation and play. Its unpredictable bounce keeps dogs engaged, promoting healthy chewing habits.",
    features: ["Durable rubber", "Stuffable for treats", "Unpredictable bounce", "Promotes chewing"],
    specs: { Material: "Natural Rubber", Size: "Large", Color: "Red", Use: "Chew toy" },
  },
  {
    id: 54,
    name: "PetSafe Automatic Ball Launcher Dog Toy",
    category: "Pet Supplies",
    price: 139.95,
    rating: 4.2,
    reviews: 8901,
    image: "https://m.media-amazon.com/images/I/71kiOXh6SDL._AC_SX679_.jpg",
    link: "https://www.amazon.com/PetSafe-Automatic-Launcher-Interactive-Included/dp/B075X3CRPF?tag=marketplaza0b-20",
    description: "Interactive ball thrower keeping dogs entertained with automatic fetching fun",
    longDescription:
      "Interactive ball thrower keeping dogs entertained with automatic fetching fun. Features adjustable range settings and multiple balls for extended play sessions.",
    features: ["Automatic fetching", "Adjustable range", "Multiple balls", "Keeps dogs active"],
    specs: { Type: "Ball Launcher", Power: "AC adapter", Range: "Adjustable", Balls: "Included" },
  },
  {
    id: 55,
    name: "Catit Flower Fountain: Cat Water Fountain",
    category: "Pet Supplies",
    price: 29.99,
    rating: 4.4,
    reviews: 45678,
    image: "https://m.media-amazon.com/images/I/71Hq+VdWj8L._AC_SX679_.jpg",
    link: "https://www.amazon.com/Catit-Flower-Fountain-Drinking-Waterfall/dp/B0146QXOB0?tag=marketplaza0b-20",
    description:
      "Fresh flowing water fountain encouraging cats to drink more with flower design and triple action filter",
    longDescription:
      "Fresh flowing water fountain encouraging cats to drink more with flower design and triple action filter. Provides filtered water at multiple flow options for picky drinkers.",
    features: ["Encourages hydration", "Flower design", "Triple action filter", "Multiple flow options"],
    specs: { Capacity: "3 Liters", Filter: "Triple Action", Material: "BPA-free", Design: "Flower" },
  },
  {
    id: 56,
    name: "Purina Pro Plan High Protein Dog Food",
    category: "Pet Supplies",
    price: 64.98,
    rating: 4.8,
    reviews: 67890,
    image: "https://m.media-amazon.com/images/I/81Hj9sxIoFL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Purina-Protein-Chicken-Weight-Formula/dp/B07L1CTKNC?tag=marketplaza0b-20",
    description: "High-protein dry dog food with real chicken supporting muscle maintenance and overall health",
    longDescription:
      "High-protein dry dog food with real chicken supporting muscle maintenance and overall health. Formulated for active dogs with antioxidants for immune support.",
    features: ["Real chicken", "Muscle maintenance", "Immune support", "Active formula"],
    specs: { Formula: "High Protein", Protein: "Chicken", Weight: "40 lbs", Type: "Dry Food" },
  },
  {
    id: 57,
    name: "FURminator deShedding Tool for Dogs",
    category: "Pet Supplies",
    price: 39.99,
    rating: 4.6,
    reviews: 123456,
    image: "https://m.media-amazon.com/images/I/71rJzjo0IhL._AC_SX679_.jpg",
    link: "https://www.amazon.com/FURminator-Long-Hair-deShedding-Large/dp/B0040QS3PO?tag=marketplaza0b-20",
    description: "Professional grooming tool reducing shedding up to 90% with stainless steel edge",
    longDescription:
      "Professional grooming tool reducing shedding up to 90% with stainless steel edge. Designed for long-haired dogs to effectively remove undercoat and loose hair.",
    features: ["Reduces shedding 90%", "Stainless steel edge", "For long hair", "Professional quality"],
    specs: { For: "Long Hair Dogs", Size: "Large", Type: "deShedding Tool", Material: "Stainless Steel" },
  },
  {
    id: 58,
    name: "SmartyKat Hot Pursuit Cat Toy",
    category: "Pet Supplies",
    price: 14.99,
    rating: 4.5,
    reviews: 34567,
    image: "https://m.media-amazon.com/images/I/81McoQ7VSOL._AC_SX679_.jpg",
    link: "https://www.amazon.com/SmartyKat-Pursuit-Electronic-Concealed-Motion/dp/B006CAO1IK?tag=marketplaza0b-20",
    description: "Electronic cat toy with concealed feather stimulating natural hunting instincts",
    longDescription:
      "Electronic cat toy with concealed feather stimulating natural hunting instincts. Moves erratically to keep cats engaged and entertained.",
    features: ["Concealed feather", "Stimulates hunting instinct", "Erratic movement", "Entertains cats"],
    specs: { Type: "Electronic", Motion: "Concealed", Batteries: "Included", Material: "Plastic" },
  },
  {
    id: 59,
    name: "Petmate Two Door Top Load Pet Kennel",
    category: "Pet Supplies",
    price: 35.99,
    rating: 4.6,
    reviews: 23456,
    image: "https://m.media-amazon.com/images/I/717xU4yPkVL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Petmate-Door-Top-Load-Kennel/dp/B00AX3KWFY?tag=marketplaza0b-20",
    description: "Durable pet carrier with top and side entry for safe comfortable travel",
    longDescription:
      "Durable pet carrier with top and side entry for safe comfortable travel. Features secure locking mechanism and ventilation for pet comfort.",
    features: ["Top & side entry", "Secure locking", "Ventilated", "Durable construction"],
    specs: { Size: "24 inch", Doors: "2", Material: "Plastic", Use: "Travel" },
  },
  {
    id: 60,
    name: "Tetra GloFish Aquarium Gravel Cleaner",
    category: "Pet Supplies",
    price: 12.99,
    rating: 4.5,
    reviews: 12345,
    image: "https://m.media-amazon.com/images/I/61rU8YZBbWL._AC_SX679_.jpg",
    link: "https://www.amazon.com/Tetra-Cleaner-Gravel-Aquariums-Freshwater/dp/B091D3DTWS?th=1&linkCode=ll1&tag=marketplaza0b-20&linkId=825a5f5eecfb329bb695d2f678461c76&language=en_US&ref_=as_li_ss_tl",
    description: "Easy-to-use aquarium vacuum siphon for cleaning gravel and maintaining healthy fish tank water",
    longDescription:
      "Easy-to-use aquarium vacuum and gravel cleaner that removes debris from gravel beds while performing water changes. Self-starting siphon design makes water changes simple and mess-free.",
    features: ["Gravel cleaning", "Water changing", "Self-starting siphon", "Easy to use"],
    specs: { Type: "Gravel Vacuum", Size: "16 inch", Use: "Freshwater tanks", Design: "Self-start" },
  },
]
